package com.retrohandheld.launcher;

public class LauncherHTML {

    public static String get() {
        return getHead() + getScript() + getScriptEnd();
    }

    private static String getHead() {
        return "<!DOCTYPE html>\n"
+ "<html><head><meta charset='UTF-8'>\n"
+ "<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>\n"
+ "<style>\n"

// CSS Variables
+ ":root {\n"
+ "  --bg: #0a0a12;\n"
+ "  --accent: #0070d1;\n"
+ "  --accent-glow: rgba(0,112,209,0.5);\n"
+ "  --text: #ffffff;\n"
+ "  --text-dim: rgba(255,255,255,0.45);\n"
+ "  --text-mid: rgba(255,255,255,0.7);\n"
+ "  --card-w: 110px;\n"
+ "  --card-h: 140px;\n"
+ "  --card-focus-w: 135px;\n"
+ "  --card-focus-h: 172px;\n"
+ "  --system-color: #0070d1;\n"
+ "}\n"

// Reset
+ "* { margin:0; padding:0; box-sizing:border-box; -webkit-tap-highlight-color:transparent; }\n"
+ "html, body { width:100%; height:100%; overflow:hidden; }\n"
+ "body { background:var(--bg); color:var(--text); font-family:'Segoe UI',system-ui,-apple-system,Helvetica,sans-serif;\n"
+ "  user-select:none; -webkit-user-select:none; }\n"

// Dynamic background
+ ".bg {\n"
+ "  position:fixed; inset:0; z-index:0; overflow:hidden;\n"
+ "  background:var(--bg);\n"
+ "  transition:background 0.8s ease;\n"
+ "}\n"
+ ".bg-grad {\n"
+ "  position:absolute; inset:-30%; width:160%; height:160%;\n"
+ "  background: radial-gradient(ellipse at 50% 60%, var(--system-color) 0%, transparent 60%);\n"
+ "  opacity:0.12;\n"
+ "  transition:all 1s ease;\n"
+ "  filter:blur(60px);\n"
+ "}\n"
+ ".bg-grad2 {\n"
+ "  position:absolute; inset:-20%; width:140%; height:140%;\n"
+ "  background: radial-gradient(ellipse at 30% 30%, var(--system-color) 0%, transparent 50%);\n"
+ "  opacity:0.06;\n"
+ "  transition:all 1.2s ease;\n"
+ "  filter:blur(80px);\n"
+ "}\n"

// Main layout
+ ".main { position:fixed; inset:0; z-index:10; display:flex; flex-direction:column; }\n"

// ===== TOP STATUS BAR =====
+ ".topbar {\n"
+ "  height:24px; display:flex; align-items:center; justify-content:space-between;\n"
+ "  padding:0 16px; flex-shrink:0;\n"
+ "}\n"
+ ".topbar-left { display:flex; align-items:center; gap:8px; }\n"
+ ".topbar-right { display:flex; align-items:center; gap:10px; }\n"
+ ".brand { font-size:10px; font-weight:600; color:rgba(255,255,255,0.3); letter-spacing:1.5px; text-transform:uppercase; }\n"
+ ".ctrl-indicator { display:flex; align-items:center; gap:4px; font-size:10px; color:var(--text-dim); }\n"
+ ".ctrl-dot { display:inline-block; width:5px; height:5px; border-radius:50%; }\n"
+ ".ctrl-dot.on { background:#00b894; box-shadow:0 0 6px #00b894; }\n"
+ ".ctrl-dot.paired { background:#fdcb6e; box-shadow:0 0 4px #fdcb6e; }\n"
+ ".ctrl-dot.off { background:#e17055; }\n"
+ ".ctrl-batt { font-size:9px; color:var(--text-dim); margin-left:2px; }\n"
+ ".ctrl-batt.low { color:#e17055; }\n"
+ ".battery-wrap { display:flex; align-items:center; gap:3px; font-size:10px; color:var(--text-dim); }\n"
+ ".batt-icon {\n"
+ "  width:20px; height:10px; border:1.5px solid rgba(255,255,255,0.4); border-radius:2px;\n"
+ "  position:relative; display:flex; align-items:center; padding:1px;\n"
+ "}\n"
+ ".batt-icon::after {\n"
+ "  content:''; position:absolute; right:-3px; top:2px;\n"
+ "  width:2px; height:5px; background:rgba(255,255,255,0.4); border-radius:0 1px 1px 0;\n"
+ "}\n"
+ ".batt-fill { height:100%; border-radius:1px; transition:width 0.5s, background 0.5s; }\n"
+ ".batt-fill.high { background:#00b894; }\n"
+ ".batt-fill.mid { background:#fdcb6e; }\n"
+ ".batt-fill.low { background:#e17055; }\n"
+ ".charge-icon { font-size:9px; color:#fdcb6e; display:none; }\n"
+ ".charge-icon.show { display:inline; }\n"
+ ".clock { font-size:10px; color:var(--text-dim); }\n"

// ===== HERO INFO AREA (selected game info) =====
+ ".hero-info {\n"
+ "  padding:4px 24px 0; flex-shrink:0; min-height:52px;\n"
+ "  display:flex; flex-direction:column; justify-content:flex-end;\n"
+ "}\n"
+ ".hero-game-title {\n"
+ "  font-size:22px; font-weight:800; color:#fff; letter-spacing:0.5px;\n"
+ "  white-space:nowrap; overflow:hidden; text-overflow:ellipsis; max-width:70vw;\n"
+ "  transition:opacity 0.25s ease;\n"
+ "  line-height:1.15;\n"
+ "}\n"
+ ".hero-game-meta {\n"
+ "  display:flex; align-items:center; gap:8px; margin-top:2px;\n"
+ "  font-size:11px; transition:opacity 0.25s ease;\n"
+ "}\n"
+ ".hero-system-badge {\n"
+ "  display:inline-block; padding:1px 8px; border-radius:4px;\n"
+ "  font-size:9px; font-weight:700; text-transform:uppercase; letter-spacing:0.5px;\n"
+ "  background:var(--system-color); color:#fff;\n"
+ "  transition:background 0.4s ease;\n"
+ "}\n"
+ ".hero-game-size { color:var(--text-dim); font-size:10px; }\n"
+ ".hero-empty {\n"
+ "  font-size:14px; color:var(--text-dim); font-weight:400;\n"
+ "}\n"

// ===== CATEGORY INDICATOR =====
+ ".category-bar {\n"
+ "  display:flex; align-items:center; justify-content:space-between;\n"
+ "  padding:6px 24px 2px; flex-shrink:0;\n"
+ "}\n"
+ ".category-name {\n"
+ "  font-size:11px; font-weight:600; color:var(--text-mid); letter-spacing:0.5px;\n"
+ "  transition:opacity 0.3s ease;\n"
+ "}\n"
+ ".category-pills {\n"
+ "  display:flex; gap:4px; align-items:center;\n"
+ "}\n"
+ ".cat-pill {\n"
+ "  width:6px; height:6px; border-radius:50%;\n"
+ "  background:rgba(255,255,255,0.15); transition:all 0.3s ease;\n"
+ "}\n"
+ ".cat-pill.active {\n"
+ "  width:16px; border-radius:3px;\n"
+ "  background:var(--system-color);\n"
+ "}\n"
+ ".category-toast {\n"
+ "  position:fixed; top:50%; left:50%; transform:translate(-50%,-50%) scale(0.9);\n"
+ "  background:rgba(0,0,0,0.85); border:1px solid rgba(255,255,255,0.15);\n"
+ "  backdrop-filter:blur(20px); -webkit-backdrop-filter:blur(20px);\n"
+ "  border-radius:12px; padding:10px 28px; z-index:90;\n"
+ "  opacity:0; transition:opacity 0.25s ease, transform 0.25s ease;\n"
+ "  pointer-events:none;\n"
+ "  font-size:16px; font-weight:700; color:#fff; text-align:center;\n"
+ "  letter-spacing:0.5px;\n"
+ "}\n"
+ ".category-toast.show {\n"
+ "  opacity:1; transform:translate(-50%,-50%) scale(1);\n"
+ "}\n"

// ===== GAME CAROUSEL =====
+ ".carousel-area {\n"
+ "  flex:1; display:flex; align-items:center; justify-content:center;\n"
+ "  position:relative; min-height:0; overflow:hidden;\n"
+ "  padding:0 10px;\n"
+ "}\n"
+ ".carousel-track {\n"
+ "  display:flex; align-items:center; justify-content:center;\n"
+ "  gap:12px; transition:transform 0.35s cubic-bezier(0.25,0.1,0.25,1);\n"
+ "  position:relative;\n"
+ "}\n"
+ ".game-card {\n"
+ "  width:var(--card-w); height:var(--card-h); flex-shrink:0;\n"
+ "  border-radius:10px; position:relative; cursor:pointer;\n"
+ "  overflow:hidden;\n"
+ "  transform:scale(0.88); opacity:0.65;\n"
+ "  transition:transform 0.35s cubic-bezier(0.25,0.1,0.25,1),\n"
+ "             opacity 0.35s ease,\n"
+ "             box-shadow 0.35s ease,\n"
+ "             border-color 0.35s ease;\n"
+ "  border:2px solid transparent;\n"
+ "  background:#1a1a2e;\n"
+ "}\n"
+ ".game-card.near {\n"
+ "  transform:scale(0.94); opacity:0.85;\n"
+ "}\n"
+ ".game-card.focused {\n"
+ "  width:var(--card-focus-w); height:var(--card-focus-h);\n"
+ "  transform:scale(1);\n"
+ "  opacity:1;\n"
+ "  border-color:rgba(255,255,255,0.8);\n"
+ "  box-shadow:0 0 20px var(--accent-glow), 0 0 50px rgba(0,112,209,0.2),\n"
+ "             0 8px 32px rgba(0,0,0,0.6);\n"
+ "  z-index:5;\n"
+ "}\n"
+ ".game-card.far {\n"
+ "  transform:scale(0.82); opacity:0.45;\n"
+ "}\n"
+ ".game-card .cover-img {\n"
+ "  width:100%; height:100%; object-fit:cover;\n"
+ "  position:absolute; inset:0;\n"
+ "  border-radius:8px;\n"
+ "}\n"
+ ".game-card .cover-img.boxart {\n"
+ "  object-fit:contain;\n"
+ "  background:linear-gradient(135deg, #1a1a2e, #0a0a12);\n"
+ "}\n"
+ ".game-card .cover-fallback {\n"
+ "  width:100%; height:100%; position:absolute; inset:0;\n"
+ "  display:flex; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  border-radius:8px; overflow:hidden;\n"
+ "}\n"
+ ".cover-fallback::before {\n"
+ "  content:''; position:absolute; inset:0;\n"
+ "  background:inherit; filter:brightness(0.7);\n"
+ "}\n"
+ ".cover-fallback::after {\n"
+ "  content:''; position:absolute; inset:0;\n"
+ "  background:linear-gradient(180deg, transparent 40%, rgba(0,0,0,0.7));\n"
+ "}\n"
+ ".cover-fallback .game-initials {\n"
+ "  font-size:28px; font-weight:900; color:rgba(255,255,255,0.15);\n"
+ "  text-transform:uppercase; letter-spacing:3px; position:absolute; top:20%;\n"
+ "  z-index:1;\n"
+ "}\n"
+ ".cover-fallback .game-title-label {\n"
+ "  font-size:10px; font-weight:700; color:rgba(255,255,255,0.95);\n"
+ "  text-align:center; padding:0 8px;\n"
+ "  max-width:100%; overflow:hidden; display:-webkit-box;\n"
+ "  -webkit-line-clamp:3; -webkit-box-orient:vertical; line-height:1.3;\n"
+ "  z-index:1; position:absolute; bottom:20px;\n"
+ "  text-shadow:0 1px 4px rgba(0,0,0,0.8);\n"
+ "}\n"
+ ".cover-fallback .game-sys-label {\n"
+ "  font-size:7px; font-weight:700; color:rgba(255,255,255,0.5);\n"
+ "  text-transform:uppercase; letter-spacing:1.5px;\n"
+ "  position:absolute; bottom:8px; z-index:1;\n"
+ "  background:rgba(0,0,0,0.4); padding:1px 6px; border-radius:3px;\n"
+ "}\n"
// Reflection/shine on focused card
+ ".game-card.focused::after {\n"
+ "  content:''; position:absolute; top:-50%; left:-50%; width:200%; height:200%;\n"
+ "  background:linear-gradient(135deg, rgba(255,255,255,0.1) 0%, transparent 50%);\n"
+ "  pointer-events:none; border-radius:8px;\n"
+ "}\n"
// No games message
+ ".no-games {\n"
+ "  display:flex; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  gap:8px; color:var(--text-dim);\n"
+ "}\n"
+ ".no-games-icon { font-size:36px; opacity:0.3; }\n"
+ ".no-games-text { font-size:14px; font-weight:600; }\n"
+ ".no-games-sub { font-size:11px; opacity:0.6; }\n"

// ===== ACTION BAR =====
+ ".action-bar {\n"
+ "  display:flex; align-items:center; justify-content:center;\n"
+ "  gap:8px; padding:4px 16px 2px; flex-shrink:0;\n"
+ "  height:48px;\n"
+ "}\n"
+ ".action-btn {\n"
+ "  height:32px; border-radius:16px; border:1px solid rgba(255,255,255,0.08); cursor:pointer;\n"
+ "  display:flex; align-items:center; justify-content:center; gap:6px;\n"
+ "  background:rgba(255,255,255,0.04); color:var(--text-dim);\n"
+ "  font-size:13px; padding:0 14px; position:relative;\n"
+ "  transition:all 0.3s ease;\n"
+ "  outline:none;\n"
+ "}\n"
+ ".action-btn .action-label {\n"
+ "  font-size:10px; white-space:nowrap; color:rgba(255,255,255,0.5);\n"
+ "  font-weight:600; letter-spacing:0.3px;\n"
+ "}\n"
+ ".action-btn.focused {\n"
+ "  background:rgba(255,255,255,0.12);\n"
+ "  border-color:rgba(255,255,255,0.3);\n"
+ "  color:#fff;\n"
+ "  transform:scale(1.08);\n"
+ "  box-shadow:0 0 15px rgba(255,255,255,0.1);\n"
+ "}\n"
+ ".action-btn.focused .action-label {\n"
+ "  color:#fff;\n"
+ "}\n"

// ===== BOTTOM HINTS =====
+ ".hints {\n"
+ "  height:20px; display:flex; align-items:center; justify-content:center;\n"
+ "  gap:14px; flex-shrink:0; padding-bottom:2px;\n"
+ "}\n"
+ ".hint { font-size:10px; color:rgba(255,255,255,0.35); display:flex; align-items:center; gap:4px; }\n"
+ ".hint-btn {\n"
+ "  display:inline-flex; align-items:center; justify-content:center;\n"
+ "  min-width:16px; height:16px; padding:0 4px; border-radius:4px; font-size:8px; font-weight:700;\n"
+ "  background:rgba(255,255,255,0.12); color:rgba(255,255,255,0.5);\n"
+ "}\n"

// ===== OVERLAYS =====
// Filter overlay
+ ".filter-overlay {\n"
+ "  position:fixed; inset:0; z-index:100;\n"
+ "  background:rgba(5,5,12,0.95); backdrop-filter:blur(20px); -webkit-backdrop-filter:blur(20px);\n"
+ "  display:none; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  padding:16px;\n"
+ "}\n"
+ ".filter-overlay.show { display:flex; }\n"
+ ".filter-tabs {\n"
+ "  display:flex; gap:4px; margin-bottom:14px;\n"
+ "  background:rgba(255,255,255,0.06); border-radius:10px; padding:3px;\n"
+ "}\n"
+ ".filter-tab {\n"
+ "  padding:7px 22px; border-radius:8px; font-size:12px; font-weight:600;\n"
+ "  color:rgba(255,255,255,0.5); cursor:pointer; transition:all 0.2s;\n"
+ "  border:2px solid transparent;\n"
+ "}\n"
+ ".filter-tab.active { background:rgba(255,255,255,0.12); color:#fff; }\n"
+ ".filter-tab.focused { border-color:rgba(255,255,255,0.6); color:#fff; }\n"
+ ".filter-grid {\n"
+ "  display:flex; flex-wrap:wrap; gap:10px; justify-content:center;\n"
+ "  max-width:600px; margin:0 0 10px;\n"
+ "}\n"
+ ".filter-item {\n"
+ "  width:130px; height:56px; border-radius:12px; border:2px solid rgba(255,255,255,0.08);\n"
+ "  display:flex; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  cursor:pointer; transition:all 0.25s ease; background:rgba(255,255,255,0.04);\n"
+ "}\n"
+ ".filter-item.focused {\n"
+ "  border-color:rgba(255,255,255,0.6); background:rgba(255,255,255,0.12);\n"
+ "  transform:scale(1.08); box-shadow:0 0 12px rgba(255,255,255,0.1);\n"
+ "}\n"
+ ".filter-item .fi-name { font-size:13px; font-weight:700; color:#fff; }\n"
+ ".filter-item .fi-count { font-size:9px; color:rgba(255,255,255,0.5); margin-top:2px; }\n"
+ ".filter-item.active { border-color:var(--accent); background:rgba(0,112,209,0.15); }\n"
+ ".filter-allbtn {\n"
+ "  margin-top:6px; padding:10px 36px; border-radius:10px; font-size:13px; font-weight:600;\n"
+ "  color:rgba(255,255,255,0.7); background:rgba(255,255,255,0.06);\n"
+ "  border:2px solid rgba(255,255,255,0.08); cursor:pointer; transition:all 0.2s;\n"
+ "}\n"
+ ".filter-allbtn.focused {\n"
+ "  border-color:rgba(255,255,255,0.6); color:#fff; background:rgba(255,255,255,0.12);\n"
+ "}\n"

// URL Download overlay in Store
+ ".store-url-section {\n"
+ "  margin:16px auto; max-width:500px; padding:16px;\n"
+ "  background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08);\n"
+ "  border-radius:12px;\n"
+ "}\n"
+ ".store-url-title { font-size:14px; font-weight:700; margin-bottom:10px; }\n"
+ ".store-url-row {\n"
+ "  display:flex; gap:8px; margin-bottom:8px;\n"
+ "}\n"
+ ".store-url-input {\n"
+ "  flex:1; height:34px; border-radius:8px; border:1px solid rgba(255,255,255,0.15);\n"
+ "  background:rgba(0,0,0,0.4); color:#fff; padding:0 10px; font-size:12px;\n"
+ "  outline:none;\n"
+ "}\n"
+ ".store-url-input:focus { border-color:var(--accent); }\n"
+ ".store-url-input::placeholder { color:rgba(255,255,255,0.25); }\n"
+ ".store-url-btn {\n"
+ "  height:34px; padding:0 18px; border-radius:8px; border:none;\n"
+ "  background:var(--accent); color:#fff; font-size:12px; font-weight:600;\n"
+ "  cursor:pointer; transition:all 0.2s;\n"
+ "}\n"
+ ".store-url-btn:hover { background:#1e90ff; }\n"
+ ".store-sys-select {\n"
+ "  height:34px; border-radius:8px; border:1px solid rgba(255,255,255,0.15);\n"
+ "  background:rgba(0,0,0,0.4); color:#fff; padding:0 8px; font-size:12px;\n"
+ "}\n"
+ ".store-progress-bar {\n"
+ "  height:3px; background:rgba(255,255,255,0.1); border-radius:2px; margin-top:8px; overflow:hidden;\n"
+ "}\n"
+ ".store-progress-fill {\n"
+ "  height:100%; background:var(--accent); border-radius:2px; width:0%; transition:width 0.3s;\n"
+ "}\n"
+ ".store-status { font-size:11px; color:var(--text-dim); margin-top:6px; }\n"

// Settings overlay
+ ".settings-overlay {\n"
+ "  position:fixed; inset:0; z-index:100;\n"
+ "  background:rgba(5,5,12,0.95); backdrop-filter:blur(20px); -webkit-backdrop-filter:blur(20px);\n"
+ "  display:none; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  padding:20px;\n"
+ "}\n"
+ ".settings-overlay.show { display:flex; }\n"
+ ".settings-box {\n"
+ "  max-width:500px; width:100%;\n"
+ "  background:rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08);\n"
+ "  border-radius:16px; padding:20px 26px;\n"
+ "}\n"
+ ".settings-title {\n"
+ "  font-size:18px; font-weight:700; margin-bottom:14px; text-align:center;\n"
+ "  color:rgba(255,255,255,0.9);\n"
+ "}\n"
+ ".settings-item {\n"
+ "  display:flex; justify-content:space-between; align-items:center;\n"
+ "  padding:7px 0; border-bottom:1px solid rgba(255,255,255,0.04);\n"
+ "  font-size:11px;\n"
+ "}\n"
+ ".settings-item:last-child { border-bottom:none; }\n"
+ ".settings-label { color:rgba(255,255,255,0.5); }\n"
+ ".settings-value { color:rgba(255,255,255,0.9); font-weight:600; }\n"

// Overlay button (used in settings)
+ ".overlay-btn {\n"
+ "  display:block; margin:0 auto; padding:8px 36px; border:2px solid transparent; border-radius:10px;\n"
+ "  background:var(--accent);\n"
+ "  color:#fff; font-size:13px; font-weight:600; cursor:pointer;\n"
+ "  transition:transform 0.2s, box-shadow 0.2s;\n"
+ "}\n"
+ ".overlay-btn.focused {\n"
+ "  transform:scale(1.05);\n"
+ "  box-shadow:0 0 20px var(--accent-glow);\n"
+ "  border-color:rgba(255,255,255,0.6);\n"
+ "}\n"
+ ".settings-power {\n"
+ "  display:flex; gap:10px; margin-top:14px; justify-content:center;\n"
+ "}\n"
+ ".power-btn {\n"
+ "  padding:8px 24px; border:2px solid transparent; border-radius:10px;\n"
+ "  font-size:12px; font-weight:600; cursor:pointer;\n"
+ "  transition:transform 0.2s, box-shadow 0.2s, border-color 0.2s;\n"
+ "}\n"
+ ".power-btn.focused { transform:scale(1.05); border-color:rgba(255,255,255,0.6); }\n"
+ ".power-btn.shutdown { background:#c0392b; color:#fff; }\n"
+ ".power-btn.shutdown.focused { box-shadow:0 0 16px rgba(192,57,43,0.5); }\n"
+ ".power-btn.reboot { background:rgba(255,255,255,0.1); color:rgba(255,255,255,0.8); }\n"
+ ".power-btn.reboot.focused { box-shadow:0 0 16px rgba(255,255,255,0.15); }\n"

// ===== PS5-STYLE STORE OVERLAY =====
+ ".store-overlay {\n"
+ "  position:fixed; inset:0; z-index:100;\n"
+ "  background:rgba(5,5,12,0.98);\n"
+ "  display:none; flex-direction:column;\n"
+ "  overflow:hidden;\n"
+ "}\n"
+ ".store-overlay.show { display:flex; }\n"

// Store header
+ ".store-header {\n"
+ "  display:flex; align-items:center; justify-content:space-between;\n"
+ "  padding:10px 20px; flex-shrink:0;\n"
+ "  border-bottom:1px solid rgba(255,255,255,0.06);\n"
+ "}\n"
+ ".store-back {\n"
+ "  display:flex; align-items:center; gap:6px; font-size:11px; color:var(--text-dim);\n"
+ "  cursor:pointer;\n"
+ "}\n"
+ ".store-back-icon { font-size:14px; }\n"
+ ".store-title-text {\n"
+ "  font-size:16px; font-weight:700; color:#fff; letter-spacing:0.5px;\n"
+ "}\n"
+ ".store-subtitle {\n"
+ "  font-size:9px; color:var(--text-dim); letter-spacing:0.5px;\n"
+ "}\n"

// Store category tabs
+ ".store-cats {\n"
+ "  display:flex; gap:6px; padding:10px 20px 8px; flex-shrink:0;\n"
+ "  overflow-x:auto; -webkit-overflow-scrolling:touch;\n"
+ "}\n"
+ ".store-cats::-webkit-scrollbar { display:none; }\n"
+ ".store-cat-pill {\n"
+ "  padding:4px 14px; border-radius:16px; font-size:10px; font-weight:600;\n"
+ "  white-space:nowrap; cursor:pointer;\n"
+ "  background:rgba(255,255,255,0.06); color:var(--text-dim);\n"
+ "  border:1px solid rgba(255,255,255,0.06);\n"
+ "  transition:all 0.25s ease;\n"
+ "}\n"
+ ".store-cat-pill.active {\n"
+ "  background:var(--accent); color:#fff;\n"
+ "  border-color:var(--accent);\n"
+ "  box-shadow:0 0 12px rgba(0,112,209,0.3);\n"
+ "}\n"
+ ".store-cat-pill.focused {\n"
+ "  border-color:rgba(255,255,255,0.5);\n"
+ "  transform:scale(1.05);\n"
+ "}\n"

// Store scrollable content
+ ".store-content {\n"
+ "  flex:1; overflow-y:auto; padding:0 20px 20px;\n"
+ "  -webkit-overflow-scrolling:touch;\n"
+ "}\n"
+ ".store-content::-webkit-scrollbar { width:3px; }\n"
+ ".store-content::-webkit-scrollbar-thumb { background:rgba(255,255,255,0.1); border-radius:3px; }\n"

// Featured section
+ ".store-section-title {\n"
+ "  font-size:13px; font-weight:700; color:rgba(255,255,255,0.8);\n"
+ "  margin:14px 0 8px; letter-spacing:0.3px;\n"
+ "}\n"
+ ".store-featured {\n"
+ "  display:flex; gap:10px; overflow-x:auto; padding-bottom:6px;\n"
+ "  -webkit-overflow-scrolling:touch;\n"
+ "}\n"
+ ".store-featured::-webkit-scrollbar { display:none; }\n"
+ ".store-feat-card {\n"
+ "  flex-shrink:0; width:200px; border-radius:12px; overflow:hidden;\n"
+ "  background:rgba(255,255,255,0.04); border:1.5px solid rgba(255,255,255,0.06);\n"
+ "  cursor:pointer; transition:all 0.25s ease;\n"
+ "  position:relative;\n"
+ "}\n"
+ ".store-feat-card.focused {\n"
+ "  border-color:rgba(255,255,255,0.6);\n"
+ "  transform:scale(1.03);\n"
+ "  box-shadow:0 0 20px rgba(0,112,209,0.3);\n"
+ "}\n"
+ ".store-feat-art {\n"
+ "  width:100%; height:100px;\n"
+ "  display:flex; align-items:center; justify-content:center;\n"
+ "  font-size:32px; font-weight:800; color:rgba(255,255,255,0.6);\n"
+ "  letter-spacing:3px;\n"
+ "}\n"
+ ".store-feat-info { padding:8px 10px; }\n"
+ ".store-feat-name { font-size:12px; font-weight:700; color:#fff; }\n"
+ ".store-feat-desc { font-size:9px; color:var(--text-dim); margin-top:2px; }\n"
+ ".store-feat-bottom {\n"
+ "  display:flex; align-items:center; justify-content:space-between; margin-top:6px;\n"
+ "}\n"
+ ".store-feat-sys {\n"
+ "  font-size:8px; font-weight:700; padding:2px 6px; border-radius:4px;\n"
+ "  text-transform:uppercase;\n"
+ "}\n"
+ ".store-feat-dl-btn {\n"
+ "  padding:3px 10px; border-radius:6px; border:none; cursor:pointer;\n"
+ "  font-size:9px; font-weight:700; color:#fff;\n"
+ "  background:linear-gradient(135deg, #0070d1, #00a8ff);\n"
+ "  transition:all 0.2s ease;\n"
+ "}\n"
+ ".store-feat-dl-btn.installed {\n"
+ "  background:linear-gradient(135deg, #00b894, #55efc4);\n"
+ "}\n"
+ ".store-feat-dl-btn.downloading { opacity:0.7; }\n"
+ ".store-feat-progress {\n"
+ "  position:absolute; bottom:0; left:0; height:3px;\n"
+ "  background:linear-gradient(90deg, #0070d1, #00a8ff);\n"
+ "  border-radius:0 0 12px 12px; width:0; transition:width 0.3s ease;\n"
+ "}\n"

// Store game grid
+ ".store-grid {\n"
+ "  display:grid; grid-template-columns:repeat(auto-fill, minmax(150px, 1fr));\n"
+ "  gap:8px;\n"
+ "}\n"
+ ".store-game-card {\n"
+ "  border-radius:10px; overflow:hidden; position:relative;\n"
+ "  background:rgba(255,255,255,0.03); border:1.5px solid rgba(255,255,255,0.05);\n"
+ "  cursor:pointer; transition:all 0.25s ease;\n"
+ "}\n"
+ ".store-game-card.focused {\n"
+ "  border-color:rgba(255,255,255,0.5);\n"
+ "  transform:scale(1.03);\n"
+ "  box-shadow:0 0 15px rgba(0,112,209,0.2);\n"
+ "}\n"
+ ".store-game-art {\n"
+ "  width:100%; height:70px;\n"
+ "  display:flex; align-items:center; justify-content:center;\n"
+ "  font-size:22px; font-weight:800; color:rgba(255,255,255,0.5);\n"
+ "  letter-spacing:2px;\n"
+ "}\n"
+ ".store-game-info { padding:6px 8px; }\n"
+ ".store-game-name { font-size:11px; font-weight:700; color:#fff; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }\n"
+ ".store-game-desc { font-size:8px; color:var(--text-dim); margin-top:1px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }\n"
+ ".store-game-bottom {\n"
+ "  display:flex; align-items:center; justify-content:space-between; margin-top:4px;\n"
+ "}\n"
+ ".store-game-meta {\n"
+ "  display:flex; align-items:center; gap:4px;\n"
+ "}\n"
+ ".store-game-sys {\n"
+ "  font-size:7px; font-weight:700; padding:1px 5px; border-radius:3px;\n"
+ "  text-transform:uppercase;\n"
+ "}\n"
+ ".store-game-size { font-size:8px; color:var(--text-dim); }\n"
+ ".store-dl-btn {\n"
+ "  padding:2px 8px; border-radius:5px; border:none; cursor:pointer;\n"
+ "  font-size:8px; font-weight:700; color:#fff;\n"
+ "  background:linear-gradient(135deg, #0070d1, #00a8ff);\n"
+ "  transition:all 0.2s ease;\n"
+ "}\n"
+ ".store-dl-btn.installed {\n"
+ "  background:linear-gradient(135deg, #00b894, #55efc4);\n"
+ "}\n"
+ ".store-dl-btn.downloading { opacity:0.7; }\n"
+ ".store-dl-btn.manual {\n"
+ "  background:rgba(255,255,255,0.1); color:var(--text-dim);\n"
+ "}\n"
+ ".store-game-progress {\n"
+ "  position:absolute; bottom:0; left:0; height:2px;\n"
+ "  background:linear-gradient(90deg, #0070d1, #00a8ff);\n"
+ "  border-radius:0 0 10px 10px; width:0; transition:width 0.3s ease;\n"
+ "}\n"

// Store "Add Your Own Games" section
+ ".store-add-section {\n"
+ "  margin-top:16px; padding:14px 16px;\n"
+ "  background:rgba(255,255,255,0.03); border:1px solid rgba(255,255,255,0.06);\n"
+ "  border-radius:12px;\n"
+ "}\n"
+ ".store-add-title {\n"
+ "  font-size:14px; font-weight:800; color:rgba(255,255,255,0.85);\n"
+ "  text-align:center; margin-bottom:10px; letter-spacing:1px;\n"
+ "}\n"
+ ".store-add-path {\n"
+ "  font-family:monospace; font-size:10px; color:#a0c4ff;\n"
+ "  background:rgba(255,255,255,0.06); padding:4px 10px; border-radius:6px;\n"
+ "  text-align:center; margin:6px 0;\n"
+ "}\n"
+ ".store-add-systems {\n"
+ "  display:flex; flex-wrap:wrap; gap:4px; justify-content:center; margin:8px 0;\n"
+ "}\n"
+ ".store-add-sys {\n"
+ "  padding:2px 8px; border-radius:6px; font-size:8px; font-weight:600;\n"
+ "  background:rgba(255,255,255,0.07); color:rgba(255,255,255,0.5);\n"
+ "}\n"
+ ".store-recs { margin-top:10px; }\n"
+ ".store-rec-line {\n"
+ "  font-size:9px; color:rgba(255,255,255,0.55); line-height:1.6;\n"
+ "  padding-left:4px;\n"
+ "}\n"
+ ".store-rec-sys {\n"
+ "  color:rgba(255,255,255,0.8); font-weight:700;\n"
+ "}\n"
+ ".store-rec-star { color:#fdcb6e; }\n"
+ ".store-add-note {\n"
+ "  font-size:9px; color:rgba(255,255,255,0.35); text-align:center; margin-top:10px;\n"
+ "}\n"

// Info toast
+ ".info-toast {\n"
+ "  position:fixed; bottom:40px; left:50%; transform:translateX(-50%) translateY(20px);\n"
+ "  background:rgba(0,0,0,0.8); border:1px solid rgba(255,255,255,0.1);\n"
+ "  backdrop-filter:blur(20px); -webkit-backdrop-filter:blur(20px);\n"
+ "  border-radius:10px; padding:8px 18px; z-index:200;\n"
+ "  opacity:0; transition:opacity 0.3s, transform 0.3s;\n"
+ "  font-size:10px; color:rgba(255,255,255,0.75); text-align:center;\n"
+ "  pointer-events:none; max-width:400px;\n"
+ "}\n"
+ ".info-toast.show { opacity:1; transform:translateX(-50%) translateY(0); }\n"

// Splash screen
+ ".splash {\n"
+ "  position:fixed; inset:0; z-index:9999; background:#0a0a12;\n"
+ "  display:flex; flex-direction:column; align-items:center; justify-content:center;\n"
+ "  transition:opacity 0.8s ease;\n"
+ "}\n"
+ ".splash.hide { opacity:0; pointer-events:none; }\n"
+ ".splash-logo {\n"
+ "  font-size:28px; font-weight:800; color:#fff; letter-spacing:4px;\n"
+ "  text-transform:uppercase; opacity:0;\n"
+ "  animation:splashFade 1.5s ease 0.3s forwards;\n"
+ "}\n"
+ ".splash-sub {\n"
+ "  font-size:10px; color:rgba(255,255,255,0.3); letter-spacing:3px;\n"
+ "  margin-top:8px; opacity:0;\n"
+ "  animation:splashFade 1.2s ease 0.8s forwards;\n"
+ "}\n"
+ ".splash-glow {\n"
+ "  width:120px; height:3px; border-radius:2px; margin-top:16px;\n"
+ "  background:linear-gradient(90deg, transparent, #0070d1, transparent);\n"
+ "  opacity:0; animation:splashFade 1s ease 1s forwards;\n"
+ "}\n"
+ "@keyframes splashFade { to { opacity:1; } }\n"

+ "</style>\n"
+ "</head>\n"
+ "<body>\n"

// Splash screen
+ "<div class='splash' id='splash'>\n"
+ "  <div class='splash-logo'>RetroStation</div>\n"
+ "  <div class='splash-sub'>GAME CONSOLE</div>\n"
+ "  <div class='splash-glow'></div>\n"
+ "</div>\n"

// Background
+ "<div class='bg'><div class='bg-grad' id='bgGrad'></div><div class='bg-grad2' id='bgGrad2'></div></div>\n"

// Main layout
+ "<div class='main'>\n"

// Top bar
+ "  <div class='topbar'>\n"
+ "    <div class='topbar-left'>\n"
+ "      <span class='brand'>RetroStation</span>\n"
+ "    </div>\n"
+ "    <div class='topbar-right'>\n"
+ "      <span class='ctrl-indicator'><span class='ctrl-dot off' id='ctrlDot'></span><span id='ctrlName'>--</span><span class='ctrl-batt' id='ctrlBatt'></span></span>\n"
+ "      <span class='charge-icon' id='chargeIcon'>&#9889;</span>\n"
+ "      <span class='battery-wrap'>\n"
+ "        <span class='batt-icon'><span class='batt-fill high' id='battFill' style='width:80%'></span></span>\n"
+ "        <span id='battPct'>--%</span>\n"
+ "      </span>\n"
+ "      <span class='clock' id='clock'>--:--</span>\n"
+ "    </div>\n"
+ "  </div>\n"

// Hero info (selected game)
+ "  <div class='hero-info' id='heroInfo'>\n"
+ "    <div class='hero-game-title' id='heroTitle'>RetroStation</div>\n"
+ "    <div class='hero-game-meta' id='heroMeta'>\n"
+ "      <span class='hero-system-badge' id='heroBadge'>--</span>\n"
+ "      <span class='hero-game-size' id='heroSize'></span>\n"
+ "    </div>\n"
+ "  </div>\n"

// Category bar
+ "  <div class='category-bar'>\n"
+ "    <div class='category-name' id='catName'>All Games</div>\n"
+ "    <div class='category-pills' id='catPills'></div>\n"
+ "  </div>\n"

// Game carousel
+ "  <div class='carousel-area' id='carouselArea'>\n"
+ "    <div class='carousel-track' id='carouselTrack'></div>\n"
+ "  </div>\n"

// Action bar
+ "  <div class='action-bar' id='actionBar'>\n"
+ "    <button class='action-btn' id='act0' onclick='activateAction(0)'>&#9654;<span class='action-label'>Filter</span></button>\n"
+ "    <button class='action-btn' id='act1' onclick='activateAction(1)'>&#9673;<span class='action-label'>Controller</span></button>\n"
+ "    <button class='action-btn' id='act2' onclick='activateAction(2)'>&#8595;<span class='action-label'>Store</span></button>\n"
+ "    <button class='action-btn' id='act3' onclick='activateAction(3)'>&#9881;<span class='action-label'>Settings</span></button>\n"
+ "  </div>\n"

// Hints
+ "  <div class='hints'>\n"
+ "    <div class='hint'><span class='hint-btn'>A</span> Play</div>\n"
+ "    <div class='hint'><span class='hint-btn'>B</span> Back</div>\n"
+ "    <div class='hint'><span class='hint-btn'>&larr;&rarr;</span> Browse</div>\n"
+ "    <div class='hint'><span class='hint-btn'>L1</span><span class='hint-btn'>R1</span> Category</div>\n"
+ "  </div>\n"

+ "</div>\n"

// Category toast
+ "<div class='category-toast' id='catToast'></div>\n"

// System/Genre Filter overlay
+ "<div class='filter-overlay' id='filterOverlay'>\n"
+ "  <div class='settings-title' style='margin-bottom:4px'>Filter Games</div>\n"
+ "  <div style='font-size:11px;color:rgba(255,255,255,0.4);margin-bottom:10px'>Use D-pad to navigate, A to select, B to go back</div>\n"
+ "  <div class='filter-tabs' id='filterTabs'>\n"
+ "    <div class='filter-tab active' id='filterTabSys' onclick='setFilterTab(0)'>By System</div>\n"
+ "    <div class='filter-tab' id='filterTabGenre' onclick='setFilterTab(1)'>By Genre</div>\n"
+ "  </div>\n"
+ "  <div class='filter-grid' id='filterGrid'></div>\n"
+ "  <div class='filter-allbtn' id='filterAllBtn' onclick='selectFilter(-1)'>All Games</div>\n"
+ "</div>\n"

// PS5-style Store overlay
+ "<div class='store-overlay' id='storeOverlay'>\n"
+ "  <div class='store-header'>\n"
+ "    <div class='store-back' onclick='closeOverlay()'>\n"
+ "      <span class='store-back-icon'>&#9664;</span>\n"
+ "      <span>Back</span>\n"
+ "    </div>\n"
+ "    <div style='text-align:center'>\n"
+ "      <div class='store-title-text'>RetroStation Store</div>\n"
+ "      <div class='store-subtitle'>Download Games</div>\n"
+ "    </div>\n"
+ "    <div style='width:50px'></div>\n"
+ "  </div>\n"
+ "  <div class='store-content' id='storeContent'>\n"
+ "    <div class='store-url-section'>\n"
+ "      <div class='store-url-title'>Download from URL</div>\n"
+ "      <div style='font-size:10px;color:rgba(255,255,255,0.4);margin-bottom:10px'>"
+ "Paste a direct ROM download link below</div>\n"
+ "      <div class='store-url-row'>\n"
+ "        <input class='store-url-input' id='storeUrlInput' type='url' placeholder='https://... .gba/.nes/.sfc/.gb/.bin/.zip'>\n"
+ "      </div>\n"
+ "      <div class='store-url-row'>\n"
+ "        <select class='store-sys-select' id='storeSysSelect'>\n"
+ "          <option value='GBA'>GBA</option><option value='GB'>Game Boy</option>\n"
+ "          <option value='GBC'>GBC</option><option value='NES'>NES</option>\n"
+ "          <option value='SNES'>SNES</option><option value='Genesis'>Genesis</option>\n"
+ "          <option value='N64'>N64</option><option value='PS1'>PS1</option>\n"
+ "          <option value='PSP'>PSP</option><option value='Dreamcast'>Dreamcast</option>\n"
+ "          <option value='NDS'>NDS</option><option value='Doom'>Doom</option><option value='Arcade'>Arcade</option>\n"
+ "        </select>\n"
+ "        <button class='store-url-btn' onclick='downloadFromUrl()'>Download</button>\n"
+ "      </div>\n"
+ "      <div class='store-progress-bar' id='storeProgressBar'><div class='store-progress-fill' id='storeProgressFill'></div></div>\n"
+ "      <div class='store-status' id='storeStatus'></div>\n"
+ "    </div>\n"
+ "    <div class='store-url-section' style='margin-top:12px'>\n"
+ "      <div class='store-url-title'>Need Help?</div>\n"
+ "      <div style='font-size:11px;color:rgba(255,255,255,0.6);line-height:1.8;text-align:center'>\n"
+ "        Ask a grown-up to help you add more games!<br>\n"
+ "        <span style='font-size:10px;color:rgba(255,255,255,0.35)'>Games can be added by connecting to a computer via USB.</span>\n"
+ "      </div>\n"
+ "    </div>\n"
+ "  </div>\n"
+ "</div>\n"

// Settings overlay
+ "<div class='settings-overlay' id='settingsOverlay'>\n"
+ "  <div class='settings-box'>\n"
+ "    <div class='settings-title'>System Information</div>\n"
+ "    <div class='settings-item'><span class='settings-label'>Console</span><span class='settings-value'>RetroStation</span></div>\n"
+ "    <div class='settings-item'><span class='settings-label'>Games</span><span class='settings-value' id='settingsGames'>--</span></div>\n"
+ "    <div class='settings-item'><span class='settings-label'>Emulator</span><span class='settings-value'>Lemuroid</span></div>\n"
+ "    <div class='settings-item'><span class='settings-label'>Battery</span><span class='settings-value' id='settingsBatt'>--%</span></div>\n"
+ "    <div class='settings-item'><span class='settings-label'>Controller</span><span class='settings-value' id='settingsCtrl'>--</span></div>\n"
+ "    <div class='settings-item'><span class='settings-label'>ROM Path</span><span class='settings-value' style='font-size:10px'>/sdcard/RetroHandheld/roms/</span></div>\n"
+ "    <div class='settings-power'>\n"
+ "      <button class='power-btn shutdown' id='settingsShutdown' onclick='doShutdown()'>Power Off</button>\n"
+ "      <button class='power-btn reboot' id='settingsReboot' onclick='doReboot()'>Reboot</button>\n"
+ "    </div>\n"
+ "    <button class='overlay-btn' id='settingsCloseBtn' onclick='closeOverlay()' style='margin-top:10px'>Close</button>\n"
+ "  </div>\n"
+ "</div>\n"

// Info toast
+ "<div class='info-toast' id='infoToast'></div>\n"

+ "";
    }

    private static String getScript() {
        return ""
// ===== JAVASCRIPT =====
+ "<script>\n"

// ===== STATE =====
+ "var allGames = [];\n"
+ "var categories = [];\n"       // [{name, system, games}]
+ "var currentCat = 0;\n"
+ "var currentGameIdx = 0;\n"
+ "var focusRow = 0;\n"          // 0=carousel, 1=action bar
+ "var actionIdx = 0;\n"
+ "var overlayOpen = null;\n"
+ "var filterTab = 0;\n"           // 0=system, 1=genre
+ "var filterFocusArea = 'grid';\n" // 'tabs', 'grid', 'allbtn'
+ "var filterGridIdx = 0;\n"
+ "var filterItemCount = 0;\n"
+ "var FILTER_COLS = 4;\n"
+ "var settingsFocusIdx = 0;\n"   // 0=shutdown, 1=reboot, 2=close
+ "var gameCount = 0;\n"
+ "var controllerPaired = false;\n"
+ "var controllerName = '';\n"
+ "var catToastTimer = null;\n"
+ "var VISIBLE_CARDS = 7;\n"

// Sound effects via Web Audio API
+ "var audioCtx = null;\n"
+ "function initAudio() { if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)(); }\n"
+ "function playTick() {\n"
+ "  try {\n"
+ "    initAudio();\n"
+ "    var o = audioCtx.createOscillator();\n"
+ "    var g = audioCtx.createGain();\n"
+ "    o.connect(g); g.connect(audioCtx.destination);\n"
+ "    o.type = 'sine'; o.frequency.value = 1200;\n"
+ "    g.gain.value = 0.06;\n"
+ "    g.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.08);\n"
+ "    o.start(); o.stop(audioCtx.currentTime + 0.08);\n"
+ "  } catch(e) {}\n"
+ "}\n"
+ "function playSelect() {\n"
+ "  try {\n"
+ "    initAudio();\n"
+ "    var o = audioCtx.createOscillator();\n"
+ "    var g = audioCtx.createGain();\n"
+ "    o.connect(g); g.connect(audioCtx.destination);\n"
+ "    o.type = 'sine'; o.frequency.value = 800;\n"
+ "    o.frequency.exponentialRampToValueAtTime(1400, audioCtx.currentTime + 0.1);\n"
+ "    g.gain.value = 0.08;\n"
+ "    g.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.15);\n"
+ "    o.start(); o.stop(audioCtx.currentTime + 0.15);\n"
+ "  } catch(e) {}\n"
+ "}\n"
+ "function playBack() {\n"
+ "  try {\n"
+ "    initAudio();\n"
+ "    var o = audioCtx.createOscillator();\n"
+ "    var g = audioCtx.createGain();\n"
+ "    o.connect(g); g.connect(audioCtx.destination);\n"
+ "    o.type = 'sine'; o.frequency.value = 1000;\n"
+ "    o.frequency.exponentialRampToValueAtTime(600, audioCtx.currentTime + 0.1);\n"
+ "    g.gain.value = 0.06;\n"
+ "    g.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.12);\n"
+ "    o.start(); o.stop(audioCtx.currentTime + 0.12);\n"
+ "  } catch(e) {}\n"
+ "}\n"
+ "function playCatSwitch() {\n"
+ "  try {\n"
+ "    initAudio();\n"
+ "    var o = audioCtx.createOscillator();\n"
+ "    var g = audioCtx.createGain();\n"
+ "    o.connect(g); g.connect(audioCtx.destination);\n"
+ "    o.type = 'triangle'; o.frequency.value = 600;\n"
+ "    o.frequency.exponentialRampToValueAtTime(900, audioCtx.currentTime + 0.12);\n"
+ "    g.gain.value = 0.07;\n"
+ "    g.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.18);\n"
+ "    o.start(); o.stop(audioCtx.currentTime + 0.18);\n"
+ "  } catch(e) {}\n"
+ "}\n"

// Game ID mapping for direct launch
+ "var gameMapping = {};\n"

// ===== STORE STATE =====
+ "var storeCatIdx = 0;\n"
+ "var storeFocusIdx = 0;\n"
+ "var storeFocusArea = 'cats';\n"  // 'cats', 'featured', 'grid', 'addSection'
+ "var storeVisibleItems = [];\n"
+ "var installedGames = {};\n"
+ "var downloadingGames = {};\n"

// ===== STORE CATALOG =====
+ "var storeCatalog = [\n"
+ "  {name:'Celeste Classic',system:'GBA',file:'CelesteClassic.gba',size:'256 KB',\n"
+ "   desc:'Award-winning precision platformer',\n"
+ "   url:'https://github.com/nicklausw/gba-celeste/releases/download/v1.0/celeste.gba',\n"
+ "   featured:true},\n"
+ "  {name:'Anguna',system:'GBA',file:'Anguna.gba',size:'256 KB',\n"
+ "   desc:'Zelda-like dungeon adventure',\n"
+ "   url:'https://www.tolberts.net/anguna/Anguna.gba',\n"
+ "   featured:true},\n"
+ "  {name:'Inheritors of the Sun',system:'GBA',file:'inheritors.gba',size:'1.2 MB',\n"
+ "   desc:'Turn-based tactical RPG',\n"
+ "   url:''},\n"
+ "  {name:'Micro Mages',system:'NES',file:'MicroMages.nes',size:'40 KB',\n"
+ "   desc:'4-player co-op platformer masterpiece',\n"
+ "   url:'',featured:true},\n"
+ "  {name:'From Below',system:'NES',file:'FromBelow.nes',size:'40 KB',\n"
+ "   desc:'Underwater block puzzle game',\n"
+ "   url:''},\n"
+ "  {name:'Cave Story MD',system:'Genesis',file:'CaveStoryMD.bin',size:'2 MB',\n"
+ "   desc:'Classic action-adventure, Genesis port',\n"
+ "   url:'',featured:true},\n"
+ "  {name:'Super Boss Gaiden',system:'SNES',file:'SuperBossGaiden.sfc',size:'512 KB',\n"
+ "   desc:'Side-scrolling action game',\n"
+ "   url:''}\n"
+ "];\n"

+ "var storeCategories = ['All','GBA','NES','SNES','Genesis','GB'];\n"

// ===== GENRE DETECTION =====
+ "var GENRE_RULES = [\n"
+ "  {name:'Platformer', color:'#e74c3c', keys:['jump','platform','mario','climb','runner','wario','donkey','kirby','sonic','mega man','megaman','metroid','castlevania','barnabe','jim','super wings']},\n"
+ "  {name:'Puzzle', color:'#9b59b6', keys:['puzzle','tetris','block','match','memory','picross','sokoban','minesweep','sudoku','trivia','tic tac','tictac','hexaviru','balle','looped','loop the','peg','rps','paper scissor','tetravex','tetrigram','clean game']},\n"
+ "  {name:'Shooter', color:'#e67e22', keys:['shoot','blast','invader','bullet','gun','shmup','galaga','blaster','eliminator','tail gun','thwaite','space','star evil','vigilante','sniper','turret','cannon']},\n"
+ "  {name:'Racing', color:'#2ecc71', keys:['race','racing','drive','kart','car','racer','downforce','crazy driver']},\n"
+ "  {name:'RPG', color:'#3498db', keys:['rpg','quest','pokemon','dungeon','dragon','knight','fantasy','furry rpg','owlia','rise of','zelda']},\n"
+ "  {name:'Action', color:'#e84393', keys:['fight','combat','battle','ninja','warrior','sword','metal','doom','war','assimilat','twin dragon','mosh','pit','paco','impact']},\n"
+ "  {name:'Sports', color:'#1abc9c', keys:['sport','ball','soccer','football','tennis','golf','basket','bowling','hockey','wrestling']},\n"
+ "  {name:'Strategy', color:'#f39c12', keys:['strategy','chess','tower','defense','tactic','command','troop','army','siege']},\n"
+ "  {name:'Arcade', color:'#7b2ff7', keys:['pong','pac','snake','flappy','brick','breakout','arkanoid','pinball','frog','gorf','worm','asteroid','debris','fixer','robot find','roulette']},\n"
+ "  {name:'Adventure', color:'#636e72', keys:['adventure','explore','cave','island','world','story','hilda','novella','escape']}\n"
+ "];\n"
+ "function detectGenre(name) {\n"
+ "  var low = (name || '').toLowerCase();\n"
+ "  for (var i = 0; i < GENRE_RULES.length; i++) {\n"
+ "    var keys = GENRE_RULES[i].keys;\n"
+ "    for (var k = 0; k < keys.length; k++) {\n"
+ "      if (low.indexOf(keys[k]) >= 0) return GENRE_RULES[i].name;\n"
+ "    }\n"
+ "  }\n"
+ "  return 'Other';\n"
+ "}\n"

// ===== SYSTEM COLORS =====
+ "var SYSTEM_COLORS = {\n"
+ "  'gba':'#7b2ff7', 'gb':'#2ecc71', 'gbc':'#9b59b6', 'nes':'#e74c3c',\n"
+ "  'snes':'#f39c12', 'genesis':'#1abc9c', 'megadrive':'#1abc9c',\n"
+ "  'doom':'#8b0000', 'n64':'#e74c3c', 'ps1':'#3498db', 'psp':'#2c3e50',\n"
+ "  'dreamcast':'#e67e22', 'arcade':'#e84393', 'nds':'#636e72',\n"
+ "  'default':'#0070d1'\n"
+ "};\n"

// ===== SYSTEM DISPLAY NAMES =====
+ "var SYSTEM_NAMES = {\n"
+ "  'gba':'Game Boy Advance', 'gb':'Game Boy', 'gbc':'Game Boy Color',\n"
+ "  'nes':'Nintendo', 'snes':'Super Nintendo', 'genesis':'Sega Genesis',\n"
+ "  'megadrive':'Sega Mega Drive', 'doom':'Doom', 'n64':'Nintendo 64',\n"
+ "  'ps1':'PlayStation', 'psp':'PlayStation Portable',\n"
+ "  'dreamcast':'Dreamcast', 'arcade':'Arcade', 'nds':'Nintendo DS'\n"
+ "};\n"

// ===== FEATURED GAMES (names to match, lowercased) =====
+ "var FEATURED = ['pokemon blue','pokemon red','pokemon emerald','pokemon crystal',\n"
+ "  'doom','celeste classic','celeste','cave story'];\n"

// ===== CLEAN GAME NAME =====
+ "function cleanName(file) {\n"
+ "  var n = file;\n"
// Remove extension
+ "  n = n.replace(/\\.[^.]+$/, '');\n"
// Remove region info in parentheses/brackets
+ "  n = n.replace(/\\s*[\\(\\[][^\\)\\]]*[\\)\\]]/g, '');\n"
// Split camelCase: insert space before uppercase letters preceded by lowercase
+ "  n = n.replace(/([a-z])([A-Z])/g, '$1 $2');\n"
// Split number-letter boundaries
+ "  n = n.replace(/([0-9])([a-zA-Z])/g, '$1 $2');\n"
+ "  n = n.replace(/([a-zA-Z])([0-9])/g, '$1 $2');\n"
// Replace underscores and hyphens with spaces
+ "  n = n.replace(/[_\\-]/g, ' ');\n"
// Collapse multiple spaces
+ "  n = n.replace(/\\s+/g, ' ');\n"
// Title case each word
+ "  n = n.replace(/\\b\\w/g, function(c) { return c.toUpperCase(); });\n"
// Handle 'Pokemon -' pattern
+ "  n = n.replace(' - ', ': ');\n"
// Trim
+ "  n = n.trim();\n"
+ "  return n || file;\n"
+ "}\n"

// ===== GET GAME INITIALS =====
+ "function getInitials(name) {\n"
+ "  var words = name.split(/\\s+/);\n"
+ "  if (words.length === 1) return name.substring(0,2).toUpperCase();\n"
+ "  return (words[0][0] + words[1][0]).toUpperCase();\n"
+ "}\n"

// ===== GET SYSTEM COLOR =====
+ "function sysColor(sys) {\n"
+ "  return SYSTEM_COLORS[(sys||'').toLowerCase()] || SYSTEM_COLORS['default'];\n"
+ "}\n"

// ===== GET SYSTEM DISPLAY NAME =====
+ "function sysDisplayName(sys) {\n"
+ "  return SYSTEM_NAMES[(sys||'').toLowerCase()] || sys.toUpperCase();\n"
+ "}\n"

// ===== FORMAT FILE SIZE =====
+ "function formatSize(bytes) {\n"
+ "  if (!bytes || bytes <= 0) return '';\n"
+ "  if (bytes < 1024) return bytes + ' B';\n"
+ "  if (bytes < 1048576) return (bytes / 1024).toFixed(0) + ' KB';\n"
+ "  return (bytes / 1048576).toFixed(1) + ' MB';\n"
+ "}\n"

// ===== LOAD GAMES =====
+ "function loadGames() {\n"
+ "  allGames = [];\n"
+ "  categories = [];\n"
+ "  try {\n"
+ "    var raw = Console.getGames();\n"
+ "    var parsed = JSON.parse(raw);\n"
// Deduplicate by lowercased name per system
+ "    var seen = {};\n"
+ "    for (var i = 0; i < parsed.length; i++) {\n"
+ "      var g = parsed[i];\n"
+ "      g.cleanName = cleanName(g.file || g.name || '');\n"
// Deduplicate by lowercase filename within system (catches nested dir dupes)
+ "      var key = (g.system || '').toLowerCase() + ':' + (g.file || '').toLowerCase();\n"
+ "      if (!seen[key]) {\n"
+ "        seen[key] = true;\n"
+ "        g.color = sysColor(g.system);\n"
+ "        g.initials = getInitials(g.cleanName);\n"
// Build cover path: covers/SYSTEM/basename.png
+ "        var basename = (g.file || '').replace(/\\.[^.]+$/, '');\n"
+ "        g.coverPath = 'covers/' + (g.system || 'unknown') + '/' + basename + '.png';\n"
+ "        allGames.push(g);\n"
+ "      }\n"
+ "    }\n"
+ "  } catch(e) {}\n"
// Load game mapping for direct launch
+ "  try {\n"
+ "    gameMapping = JSON.parse(Console.getGameMapping());\n"
+ "  } catch(e) { gameMapping = {}; }\n"
// Build categories
+ "  buildCategories();\n"
+ "}\n"

// ===== BUILD CATEGORIES =====
+ "function buildCategories() {\n"
+ "  categories = [];\n"
+ "  if (allGames.length === 0) return;\n"

// Recently Played category (Fix #1)
+ "  var recentGames = [];\n"
+ "  try {\n"
+ "    var recentStr = Console.getRecentGames();\n"
+ "    if (recentStr) {\n"
+ "      var entries = recentStr.split('\\n');\n"
+ "      for (var r = 0; r < entries.length; r++) {\n"
+ "        var parts = entries[r].split('|');\n"
+ "        if (parts.length >= 2) {\n"
+ "          var rSys = parts[0], rPath = parts[1];\n"
+ "          var rFile = rPath.split('/').pop();\n"
+ "          for (var g = 0; g < allGames.length; g++) {\n"
+ "            if (allGames[g].file === rFile) {\n"
+ "              recentGames.push(allGames[g]);\n"
+ "              break;\n"
+ "            }\n"
+ "          }\n"
+ "        }\n"
+ "      }\n"
+ "    }\n"
+ "  } catch(e) {}\n"
+ "  if (recentGames.length > 0) {\n"
+ "    categories.push({name:'Recently Played', system:null, games:recentGames});\n"
+ "  }\n"

// All Games category with featured first
+ "  var featured = [];\n"
+ "  var featuredSet = {};\n"
+ "  for (var f = 0; f < FEATURED.length; f++) {\n"
+ "    for (var g = 0; g < allGames.length; g++) {\n"
+ "      if (allGames[g].cleanName.toLowerCase().indexOf(FEATURED[f]) >= 0 && !featuredSet[g]) {\n"
+ "        featured.push(allGames[g]);\n"
+ "        featuredSet[g] = true;\n"
+ "        break;\n"
+ "      }\n"
+ "    }\n"
+ "  }\n"
+ "  for (var g = 0; g < allGames.length; g++) {\n"
+ "    if (!featuredSet[g]) featured.push(allGames[g]);\n"
+ "  }\n"
+ "  categories.push({name:'All Games', system:null, games:featured});\n"

// Per-system categories
+ "  var systemMap = {};\n"
+ "  var systemOrder = [];\n"
+ "  for (var i = 0; i < allGames.length; i++) {\n"
+ "    var sys = (allGames[i].system || 'unknown').toLowerCase();\n"
+ "    if (!systemMap[sys]) {\n"
+ "      systemMap[sys] = [];\n"
+ "      systemOrder.push(sys);\n"
+ "    }\n"
+ "    systemMap[sys].push(allGames[i]);\n"
+ "  }\n"
// Sort systems by game count desc
+ "  systemOrder.sort(function(a,b) { return systemMap[b].length - systemMap[a].length; });\n"
+ "  for (var s = 0; s < systemOrder.length; s++) {\n"
+ "    var sys = systemOrder[s];\n"
+ "    if (systemMap[sys].length === 0) continue;\n"  // Fix #14: skip empty systems
+ "    categories.push({\n"
+ "      name: sysDisplayName(sys),\n"
+ "      system: sys,\n"
+ "      games: systemMap[sys]\n"
+ "    });\n"
+ "  }\n"
+ "}\n"

// ===== RENDER CATEGORY PILLS =====
+ "function renderCatPills() {\n"
+ "  var el = document.getElementById('catPills');\n"
+ "  var html = '';\n"
+ "  for (var i = 0; i < categories.length; i++) {\n"
+ "    html += '<div class=\"cat-pill' + (i === currentCat ? ' active' : '') + '\"></div>';\n"
+ "  }\n"
+ "  el.innerHTML = html;\n"
+ "}\n"

// ===== RENDER CAROUSEL =====
+ "function renderCarousel() {\n"
+ "  var track = document.getElementById('carouselTrack');\n"
+ "  if (categories.length === 0 || !categories[currentCat] || categories[currentCat].games.length === 0) {\n"
+ "    track.innerHTML = '<div class=\"no-games\"><div class=\"no-games-icon\">&#127918;</div>'\n"
+ "      + '<div class=\"no-games-text\">No Games Found</div>'\n"
+ "      + '<div class=\"no-games-sub\">Press Down then select Store to add games</div></div>';\n"
+ "    document.getElementById('heroTitle').textContent = 'RetroStation';\n"
+ "    document.getElementById('heroBadge').style.display = 'none';\n"
+ "    document.getElementById('heroSize').textContent = '';\n"
+ "    return;\n"
+ "  }\n"
+ "  var games = categories[currentCat].games;\n"
+ "  var html = '';\n"
// We render all cards, JS will manage visibility classes
+ "  for (var i = 0; i < games.length; i++) {\n"
+ "    var g = games[i];\n"
+ "    var sysLower = (g.system || '').toLowerCase();\n"
+ "    var cardColor = g.color || sysColor(sysLower);\n"
+ "    html += '<div class=\"game-card\" data-idx=\"' + i + '\" onclick=\"selectGameCard(' + i + ')\"'\n"
+ "      + ' style=\"--card-color:' + cardColor + '\">';\n"
+ "    var isBoxart = g.cleanName.toLowerCase().indexOf('pokemon') >= 0\n"
+ "      || g.cleanName.toLowerCase().indexOf('doom') >= 0\n"
+ "      || g.cleanName.toLowerCase().indexOf('celeste classic') >= 0;\n"
+ "    html += '<img class=\"cover-img' + (isBoxart ? ' boxart' : '') + '\" src=\"' + g.coverPath + '\"'\n"
+ "      + ' onerror=\"this.style.display=\\'none\\';this.nextElementSibling.style.display=\\'flex\\'\"';\n"
+ "    html += '>';\n"
+ "    html += '<div class=\"cover-fallback\" style=\"display:none;background:linear-gradient(135deg,' + cardColor + ',rgba(0,0,0,0.8))\">';\n"
+ "    html += '<span class=\"game-initials\">' + g.initials + '</span>';\n"
+ "    html += '<span class=\"game-title-label\">' + g.cleanName + '</span>';\n"
+ "    html += '<span class=\"game-sys-label\">' + (g.system || '').toUpperCase() + '</span>';\n"
+ "    html += '</div></div>';\n"
+ "  }\n"
+ "  track.innerHTML = html;\n"
+ "  updateCarouselFocus(false);\n"
+ "}\n"

// ===== UPDATE CAROUSEL FOCUS =====
+ "function updateCarouselFocus(animate) {\n"
+ "  if (categories.length === 0) return;\n"
+ "  var games = categories[currentCat].games;\n"
+ "  if (games.length === 0) return;\n"
// Wrap index
+ "  if (currentGameIdx < 0) currentGameIdx = games.length - 1;\n"
+ "  if (currentGameIdx >= games.length) currentGameIdx = 0;\n"

+ "  var cards = document.getElementById('carouselTrack').children;\n"
+ "  for (var i = 0; i < cards.length; i++) {\n"
+ "    var dist = Math.abs(i - currentGameIdx);\n"
// Handle wrap-around distance
+ "    var wrapDist = Math.abs(i - currentGameIdx + games.length);\n"
+ "    var wrapDist2 = Math.abs(i - currentGameIdx - games.length);\n"
+ "    dist = Math.min(dist, wrapDist, wrapDist2);\n"
+ "    cards[i].classList.remove('focused','near','far');\n"
+ "    if (i === currentGameIdx) {\n"
+ "      cards[i].classList.add('focused');\n"
+ "    } else if (dist === 1) {\n"
+ "      cards[i].classList.add('near');\n"
+ "    } else if (dist > 3) {\n"
+ "      cards[i].classList.add('far');\n"
+ "    }\n"
// Hide cards too far away
+ "    if (dist > Math.floor(VISIBLE_CARDS / 2) + 1) {\n"
+ "      cards[i].style.display = 'none';\n"
+ "    } else {\n"
+ "      cards[i].style.display = '';\n"
+ "    }\n"
+ "  }\n"

// Scroll focused card to center
+ "  var focusedCard = cards[currentGameIdx];\n"
+ "  if (focusedCard) {\n"
+ "    var area = document.getElementById('carouselArea');\n"
+ "    var areaW = area.offsetWidth;\n"
// Calculate offset to center the focused card
+ "    var allCards = document.getElementById('carouselTrack').querySelectorAll('.game-card');\n"
+ "    var offset = 0;\n"
+ "    for (var i = 0; i < currentGameIdx; i++) {\n"
+ "      if (allCards[i].style.display !== 'none') {\n"
+ "        offset += allCards[i].offsetWidth + 12;\n"
+ "      }\n"
+ "    }\n"
// Center the focused card
+ "    var focusW = focusedCard.offsetWidth;\n"
+ "    var trackEl = document.getElementById('carouselTrack');\n"
+ "    var trackW = trackEl.scrollWidth;\n"
+ "    var centerOffset = (areaW / 2) - offset - (focusW / 2);\n"
+ "    trackEl.style.transform = 'translateX(' + centerOffset + 'px)';\n"
+ "  }\n"

// Update hero info
+ "  var g = games[currentGameIdx];\n"
+ "  document.getElementById('heroTitle').textContent = g.cleanName;\n"
+ "  var badge = document.getElementById('heroBadge');\n"
+ "  badge.style.display = '';\n"
+ "  badge.textContent = (g.system || '').toUpperCase();\n"
+ "  badge.style.background = g.color;\n"
+ "  document.getElementById('heroSize').textContent = formatSize(g.size);\n"

// Update background color
+ "  var color = g.color || SYSTEM_COLORS['default'];\n"
+ "  document.documentElement.style.setProperty('--system-color', color);\n"
+ "  document.getElementById('bgGrad').style.background = 'radial-gradient(ellipse at 50% 60%, ' + color + ' 0%, transparent 60%)';\n"
+ "  document.getElementById('bgGrad2').style.background = 'radial-gradient(ellipse at 30% 30%, ' + color + ' 0%, transparent 50%)';\n"

// Update category name
+ "  document.getElementById('catName').textContent = categories[currentCat].name\n"
+ "    + ' (' + games.length + ')';\n"
+ "}\n"

// ===== SELECT GAME CARD (click) =====
+ "function selectGameCard(idx) {\n"
+ "  focusRow = 0;\n"
+ "  currentGameIdx = idx;\n"
+ "  updateCarouselFocus(true);\n"
+ "  clearActionFocus();\n"
+ "}\n"

// ===== SWITCH CATEGORY =====
+ "function switchCategory(dir) {\n"
+ "  if (categories.length <= 1) return;\n"
+ "  currentCat += dir;\n"
+ "  if (currentCat < 0) currentCat = categories.length - 1;\n"
+ "  if (currentCat >= categories.length) currentCat = 0;\n"
+ "  currentGameIdx = 0;\n"
+ "  renderCarousel();\n"
+ "  renderCatPills();\n"
// Show category toast
+ "  showCatToast(categories[currentCat].name);\n"
+ "}\n"

// ===== SHOW CATEGORY TOAST =====
+ "function showCatToast(name) {\n"
+ "  var t = document.getElementById('catToast');\n"
+ "  t.textContent = name;\n"
+ "  t.classList.add('show');\n"
+ "  clearTimeout(catToastTimer);\n"
+ "  catToastTimer = setTimeout(function() { t.classList.remove('show'); }, 1200);\n"
+ "}\n"

// ===== ACTION BAR FOCUS =====
+ "function setActionFocus(idx) {\n"
+ "  for (var i = 0; i < 4; i++) {\n"
+ "    document.getElementById('act' + i).classList.remove('focused');\n"
+ "  }\n"
+ "  if (idx >= 0 && idx < 4) {\n"
+ "    actionIdx = idx;\n"
+ "    document.getElementById('act' + idx).classList.add('focused');\n"
+ "  }\n"
+ "}\n"
+ "function clearActionFocus() {\n"
+ "  for (var i = 0; i < 4; i++) {\n"
+ "    document.getElementById('act' + i).classList.remove('focused');\n"
+ "  }\n"
+ "}\n"

// ===== ACTIVATE ACTION =====
+ "function activateAction(idx) {\n"
+ "  actionIdx = idx;\n"
+ "  focusRow = 1;\n"
+ "  setActionFocus(idx);\n"
+ "  if (idx === 0) {\n"
+ "    openFilterOverlay();\n"
+ "  } else if (idx === 1) {\n"
+ "    try { Console.openBluetoothSettings(); } catch(e) {}\n"
+ "  } else if (idx === 2) {\n"
+ "    openStoreOverlay();\n"
+ "  } else if (idx === 3) {\n"
+ "    openSettingsOverlay();\n"
+ "  }\n"
+ "}\n"

// ===== NAVIGATION (called by Android) =====
+ "function navigate(dir) {\n"
// Overlay-specific navigation
+ "  if (overlayOpen === 'store') {\n"
+ "    navigateStore(dir);\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen === 'filter') {\n"
+ "    navigateFilter(dir);\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen === 'settings') {\n"
+ "    navigateSettings(dir);\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen) return;\n"
+ "  playTick();\n"
+ "  if (dir === 'left') {\n"
+ "    if (focusRow === 0) {\n"
// Move left in carousel
+ "      currentGameIdx--;\n"
+ "      if (categories.length > 0 && categories[currentCat].games.length > 0) {\n"
+ "        if (currentGameIdx < 0) currentGameIdx = categories[currentCat].games.length - 1;\n"
+ "      }\n"
+ "      updateCarouselFocus(true);\n"
+ "    } else {\n"
+ "      actionIdx--;\n"
+ "      if (actionIdx < 0) actionIdx = 3;\n"
+ "      setActionFocus(actionIdx);\n"
+ "    }\n"
+ "  } else if (dir === 'right') {\n"
+ "    if (focusRow === 0) {\n"
+ "      currentGameIdx++;\n"
+ "      if (categories.length > 0 && categories[currentCat].games.length > 0) {\n"
+ "        if (currentGameIdx >= categories[currentCat].games.length) currentGameIdx = 0;\n"
+ "      }\n"
+ "      updateCarouselFocus(true);\n"
+ "    } else {\n"
+ "      actionIdx++;\n"
+ "      if (actionIdx > 3) actionIdx = 0;\n"
+ "      setActionFocus(actionIdx);\n"
+ "    }\n"
+ "  } else if (dir === 'down') {\n"
+ "    if (focusRow === 0) {\n"
+ "      focusRow = 1;\n"
+ "      setActionFocus(actionIdx);\n"
+ "    }\n"
+ "  } else if (dir === 'up') {\n"
+ "    if (focusRow === 1) {\n"
+ "      focusRow = 0;\n"
+ "      clearActionFocus();\n"
+ "      updateCarouselFocus(true);\n"
+ "    }\n"
+ "  } else if (dir === 'l1') {\n"
+ "    playCatSwitch();\n"
+ "    switchCategory(-1);\n"
+ "  } else if (dir === 'r1') {\n"
+ "    playCatSwitch();\n"
+ "    switchCategory(1);\n"
+ "  }\n"
+ "}\n"

// ===== SELECT CURRENT (A/Enter) - DIRECT GAME LAUNCH =====
+ "function selectCurrent() {\n"
+ "  if (overlayOpen === 'store') {\n"
+ "    selectStoreItem();\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen === 'filter') {\n"
+ "    selectFilterItem();\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen === 'settings') {\n"
+ "    selectSettingsItem();\n"
+ "    return;\n"
+ "  }\n"
+ "  if (overlayOpen) {\n"
+ "    closeOverlay();\n"
+ "    return;\n"
+ "  }\n"
+ "  if (focusRow === 0) {\n"
// Carousel: launch game DIRECTLY
+ "    playSelect();\n"
+ "    if (categories.length > 0 && categories[currentCat].games.length > 0) {\n"
+ "      var game = categories[currentCat].games[currentGameIdx];\n"
+ "      if (game) {\n"
+ "        try {\n"
+ "          var gameId = Console.getLemuroidGameId(game.file);\n"
+ "          if (gameId > 0) {\n"
+ "            Console.launchLemuroidGame(gameId);\n"
+ "          } else {\n"
+ "            Console.launchLemuroid();\n"
+ "          }\n"
+ "        } catch(e) {\n"
+ "          try { Console.launchLemuroid(); } catch(e2) { showToast('Lemuroid not installed'); }\n"
+ "        }\n"
+ "      }\n"
+ "    }\n"
+ "  } else {\n"
// Action bar
+ "    activateAction(actionIdx);\n"
+ "  }\n"
+ "}\n"

// ===== GO BACK (B/Back) =====
+ "function goBack() {\n"
+ "  playBack();\n"
+ "  if (overlayOpen) {\n"
+ "    closeOverlay();\n"
+ "    return;\n"
+ "  }\n"
// If on action bar, go back to carousel
+ "  if (focusRow === 1) {\n"
+ "    focusRow = 0;\n"
+ "    clearActionFocus();\n"
+ "    updateCarouselFocus(true);\n"
+ "  }\n"
+ "}\n"

// ===== TOGGLE MENU (Start) =====
+ "function toggleMenu() {\n"
+ "  if (overlayOpen) {\n"
+ "    closeOverlay();\n"
+ "  } else {\n"
+ "    openSettingsOverlay();\n"
+ "  }\n"
+ "}\n"

// ===== SHOW INFO (Y button) =====
+ "function showInfo() {\n"
+ "  if (overlayOpen) return;\n"
+ "  if (focusRow === 0 && categories.length > 0 && categories[currentCat].games.length > 0) {\n"
+ "    var g = categories[currentCat].games[currentGameIdx];\n"
+ "    var msg = g.cleanName + '  |  ' + sysDisplayName(g.system)\n"
+ "      + (g.size ? '  |  ' + formatSize(g.size) : '')\n"
+ "      + (g.file ? '  |  ' + g.file : '');\n"
+ "    showToast(msg);\n"
+ "  } else {\n"
+ "    showToast('RetroStation  |  ' + gameCount + ' games  |  '\n"
+ "      + (controllerPaired ? controllerName : 'No controller'));\n"
+ "  }\n"
+ "}\n"

+ "";
    }

    private static String getScriptEnd() {
        return ""
// ===== STORE OVERLAY FUNCTIONS =====
+ "function openStoreOverlay() {\n"
+ "  document.getElementById('storeOverlay').classList.add('show');\n"
+ "  overlayOpen = 'store';\n"
+ "}\n"

+ "function renderStore() {\n"
// Render category pills
+ "  var catsHtml = '';\n"
+ "  for (var i = 0; i < storeCategories.length; i++) {\n"
+ "    catsHtml += '<div class=\"store-cat-pill' + (i === storeCatIdx ? ' active' : '') + '\"'\n"
+ "      + ' data-store-cat=\"' + i + '\" onclick=\"setStoreCat(' + i + ')\">' + storeCategories[i] + '</div>';\n"
+ "  }\n"
+ "  document.getElementById('storeCats').innerHTML = catsHtml;\n"

// Filter games by selected category
+ "  var cat = storeCategories[storeCatIdx];\n"
+ "  var filtered = [];\n"
+ "  for (var i = 0; i < storeCatalog.length; i++) {\n"
+ "    if (cat === 'All' || storeCatalog[i].system === cat) {\n"
+ "      filtered.push(storeCatalog[i]);\n"
+ "    }\n"
+ "  }\n"

// Build visible items list for navigation
+ "  storeVisibleItems = [];\n"

// Featured section
+ "  var featHtml = '';\n"
+ "  var featGames = [];\n"
+ "  for (var i = 0; i < filtered.length; i++) {\n"
+ "    if (filtered[i].featured) featGames.push(filtered[i]);\n"
+ "  }\n"
+ "  if (featGames.length > 0) {\n"
+ "    featHtml += '<div class=\"store-section-title\">Featured</div>';\n"
+ "    featHtml += '<div class=\"store-featured\">';\n"
+ "    for (var i = 0; i < featGames.length; i++) {\n"
+ "      var g = featGames[i];\n"
+ "      var color = sysColor(g.system);\n"
+ "      var dlState = getDownloadState(g);\n"
+ "      storeVisibleItems.push({type:'featured', game:g, idx:storeVisibleItems.length});\n"
+ "      featHtml += '<div class=\"store-feat-card\" data-store-item=\"' + (storeVisibleItems.length - 1) + '\">';\n"
+ "      featHtml += '<div class=\"store-feat-art\" style=\"background:linear-gradient(135deg,' + color + ',rgba(0,0,0,0.8))\">';\n"
+ "      featHtml += getInitials(g.name);\n"
+ "      featHtml += '</div>';\n"
+ "      featHtml += '<div class=\"store-feat-info\">';\n"
+ "      featHtml += '<div class=\"store-feat-name\">' + g.name + '</div>';\n"
+ "      featHtml += '<div class=\"store-feat-desc\">' + g.desc + '</div>';\n"
+ "      featHtml += '<div class=\"store-feat-bottom\">';\n"
+ "      featHtml += '<span class=\"store-feat-sys\" style=\"background:' + color + '\">' + g.system + '</span>';\n"
+ "      featHtml += '<span class=\"store-feat-dl-btn ' + dlState.cls + '\" data-file=\"' + g.file + '\">' + dlState.label + '</span>';\n"
+ "      featHtml += '</div></div>';\n"
+ "      featHtml += '<div class=\"store-feat-progress\" id=\"prog-' + g.file.replace(/[^a-zA-Z0-9]/g,'_') + '\"></div>';\n"
+ "      featHtml += '</div>';\n"
+ "    }\n"
+ "    featHtml += '</div>';\n"
+ "  }\n"

// All games grid
+ "  var gridHtml = '<div class=\"store-section-title\">All Free Homebrew</div>';\n"
+ "  gridHtml += '<div class=\"store-grid\">';\n"
+ "  for (var i = 0; i < filtered.length; i++) {\n"
+ "    var g = filtered[i];\n"
+ "    var color = sysColor(g.system);\n"
+ "    var dlState = getDownloadState(g);\n"
+ "    storeVisibleItems.push({type:'grid', game:g, idx:storeVisibleItems.length});\n"
+ "    gridHtml += '<div class=\"store-game-card\" data-store-item=\"' + (storeVisibleItems.length - 1) + '\">';\n"
+ "    gridHtml += '<div class=\"store-game-art\" style=\"background:linear-gradient(135deg,' + color + ',rgba(0,0,0,0.7))\">';\n"
+ "    gridHtml += getInitials(g.name);\n"
+ "    gridHtml += '</div>';\n"
+ "    gridHtml += '<div class=\"store-game-info\">';\n"
+ "    gridHtml += '<div class=\"store-game-name\">' + g.name + '</div>';\n"
+ "    gridHtml += '<div class=\"store-game-desc\">' + g.desc + '</div>';\n"
+ "    gridHtml += '<div class=\"store-game-bottom\">';\n"
+ "    gridHtml += '<div class=\"store-game-meta\">';\n"
+ "    gridHtml += '<span class=\"store-game-sys\" style=\"background:' + color + '\">' + g.system + '</span>';\n"
+ "    gridHtml += '<span class=\"store-game-size\">' + g.size + '</span>';\n"
+ "    gridHtml += '</div>';\n"
+ "    gridHtml += '<span class=\"store-dl-btn ' + dlState.cls + '\" data-file=\"' + g.file + '\">' + dlState.label + '</span>';\n"
+ "    gridHtml += '</div></div>';\n"
+ "    gridHtml += '<div class=\"store-game-progress\" id=\"prog-' + g.file.replace(/[^a-zA-Z0-9]/g,'_') + '\"></div>';\n"
+ "    gridHtml += '</div>';\n"
+ "  }\n"
+ "  gridHtml += '</div>';\n"

// "Add Your Own Games" section
+ "  var addHtml = '<div class=\"store-add-section\">';\n"
+ "  addHtml += '<div class=\"store-add-title\">ADD YOUR OWN GAMES</div>';\n"
+ "  addHtml += '<div style=\"font-size:10px;color:rgba(255,255,255,0.55);text-align:center\">Connect your phone via USB and copy ROM files to:</div>';\n"
+ "  addHtml += '<div class=\"store-add-path\">/sdcard/RetroHandheld/roms/[SYSTEM]/</div>';\n"
+ "  addHtml += '<div style=\"font-size:9px;color:rgba(255,255,255,0.45);text-align:center;margin-bottom:4px\">Supported systems:</div>';\n"
+ "  addHtml += '<div class=\"store-add-systems\">';\n"
+ "  var systems = ['GBA','GB','GBC','NES','SNES','Genesis','NDS','N64','PS1','PSP','Dreamcast','Doom','Arcade'];\n"
+ "  for (var i = 0; i < systems.length; i++) {\n"
+ "    addHtml += '<span class=\"store-add-sys\">' + systems[i] + '</span>';\n"
+ "  }\n"
+ "  addHtml += '</div>';\n"

+ "  addHtml += '<div class=\"store-section-title\" style=\"margin-top:12px;font-size:11px\">RECOMMENDED TOP GAMES BY SYSTEM</div>';\n"
+ "  addHtml += '<div class=\"store-recs\">';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">GBA:</span> Pokemon Emerald, Zelda Minish Cap, Metroid Fusion, Castlevania Aria of Sorrow, Fire Emblem, Advance Wars</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">SNES:</span> Chrono Trigger, Zelda Link to Past, Super Metroid, Final Fantasy VI, Super Mario World, EarthBound</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">NES:</span> Super Mario Bros 3, Zelda, Mega Man 2, Castlevania</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">Genesis:</span> Sonic 2/3, Streets of Rage 2, Gunstar Heroes</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">N64:</span> Mario 64, Zelda Ocarina of Time, Mario Kart 64</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">PS1:</span> Final Fantasy VII, Castlevania SOTN, Crash Bandicoot, Metal Gear Solid, Spyro, Resident Evil</div>';\n"
+ "  addHtml += '<div class=\"store-rec-line\"><span class=\"store-rec-star\">&#9733;</span> <span class=\"store-rec-sys\">PSP:</span> God of War, Crisis Core FF7, GTA Liberty City</div>';\n"
+ "  addHtml += '</div>';\n"
+ "  addHtml += '<div class=\"store-add-note\">After adding games, they will appear in your carousel automatically.</div>';\n"
+ "  addHtml += '</div>';\n"

+ "  document.getElementById('storeContent').innerHTML = featHtml + gridHtml + addHtml;\n"
+ "}\n"

+ "function getDownloadState(game) {\n"
+ "  if (installedGames[game.file]) return {cls:'installed', label:'Installed'};\n"
+ "  if (downloadingGames[game.file]) return {cls:'downloading', label:'Downloading...'};\n"
+ "  if (!game.url) return {cls:'manual', label:'itch.io'};\n"
+ "  return {cls:'', label:'Download'};\n"
+ "}\n"

+ "function setStoreCat(idx) {\n"
+ "  storeCatIdx = idx;\n"
+ "  storeFocusIdx = 0;\n"
+ "  storeFocusArea = 'cats';\n"
+ "  renderStore();\n"
+ "  updateStoreFocus();\n"
+ "}\n"

+ "function updateStoreFocus() {\n"
// Clear all focused states
+ "  var pills = document.querySelectorAll('.store-cat-pill');\n"
+ "  for (var i = 0; i < pills.length; i++) pills[i].classList.remove('focused');\n"
+ "  var items = document.querySelectorAll('.store-feat-card,.store-game-card');\n"
+ "  for (var i = 0; i < items.length; i++) items[i].classList.remove('focused');\n"

+ "  if (storeFocusArea === 'cats') {\n"
+ "    if (pills[storeCatIdx]) pills[storeCatIdx].classList.add('focused');\n"
+ "  } else if (storeFocusArea === 'items') {\n"
+ "    var el = document.querySelector('[data-store-item=\"' + storeFocusIdx + '\"]');\n"
+ "    if (el) {\n"
+ "      el.classList.add('focused');\n"
// Scroll into view
+ "      el.scrollIntoView({behavior:'smooth', block:'nearest'});\n"
+ "    }\n"
+ "  }\n"
+ "}\n"

+ "function navigateStore(dir) {\n"
+ "  if (dir === 'left') {\n"
+ "    if (storeFocusArea === 'cats') {\n"
+ "      storeCatIdx--;\n"
+ "      if (storeCatIdx < 0) storeCatIdx = storeCategories.length - 1;\n"
+ "      setStoreCat(storeCatIdx);\n"
+ "    } else if (storeFocusArea === 'items') {\n"
+ "      storeFocusIdx--;\n"
+ "      if (storeFocusIdx < 0) storeFocusIdx = storeVisibleItems.length - 1;\n"
+ "      updateStoreFocus();\n"
+ "    }\n"
+ "  } else if (dir === 'right') {\n"
+ "    if (storeFocusArea === 'cats') {\n"
+ "      storeCatIdx++;\n"
+ "      if (storeCatIdx >= storeCategories.length) storeCatIdx = 0;\n"
+ "      setStoreCat(storeCatIdx);\n"
+ "    } else if (storeFocusArea === 'items') {\n"
+ "      storeFocusIdx++;\n"
+ "      if (storeFocusIdx >= storeVisibleItems.length) storeFocusIdx = 0;\n"
+ "      updateStoreFocus();\n"
+ "    }\n"
+ "  } else if (dir === 'down') {\n"
+ "    if (storeFocusArea === 'cats') {\n"
+ "      storeFocusArea = 'items';\n"
+ "      storeFocusIdx = 0;\n"
+ "      updateStoreFocus();\n"
+ "    } else if (storeFocusArea === 'items') {\n"
+ "      storeFocusIdx++;\n"
+ "      if (storeFocusIdx >= storeVisibleItems.length) storeFocusIdx = storeVisibleItems.length - 1;\n"
+ "      updateStoreFocus();\n"
+ "    }\n"
+ "  } else if (dir === 'up') {\n"
+ "    if (storeFocusArea === 'items') {\n"
+ "      if (storeFocusIdx <= 0) {\n"
+ "        storeFocusArea = 'cats';\n"
+ "        updateStoreFocus();\n"
+ "      } else {\n"
+ "        storeFocusIdx--;\n"
+ "        updateStoreFocus();\n"
+ "      }\n"
+ "    }\n"
+ "  }\n"
+ "}\n"

+ "function selectStoreItem() {\n"
+ "  if (storeFocusArea === 'cats') {\n"
// Pressing A on a category selects it (already handled by setStoreCat)
+ "    return;\n"
+ "  }\n"
+ "  if (storeFocusArea === 'items' && storeVisibleItems[storeFocusIdx]) {\n"
+ "    var item = storeVisibleItems[storeFocusIdx];\n"
+ "    var game = item.game;\n"
+ "    if (installedGames[game.file]) {\n"
+ "      showToast(game.name + ' is already installed');\n"
+ "      return;\n"
+ "    }\n"
+ "    if (downloadingGames[game.file]) {\n"
+ "      showToast('Already downloading ' + game.name + '...');\n"
+ "      return;\n"
+ "    }\n"
+ "    if (!game.url) {\n"
+ "      showToast(game.name + ' - Available on itch.io. Add manually via USB.');\n"
+ "      return;\n"
+ "    }\n"
// Start download
+ "    downloadingGames[game.file] = true;\n"
+ "    renderStore();\n"
+ "    updateStoreFocus();\n"
+ "    try {\n"
+ "      Console.downloadGame(game.url, game.system, game.file);\n"
+ "      showToast('Downloading ' + game.name + '...');\n"
+ "    } catch(e) {\n"
+ "      showToast('Download failed: ' + e);\n"
+ "      delete downloadingGames[game.file];\n"
+ "      renderStore();\n"
+ "      updateStoreFocus();\n"
+ "    }\n"
+ "  }\n"
+ "}\n"

// ===== DOWNLOAD CALLBACKS (called by Java bridge) =====
+ "function onDownloadProgress(percent, filename) {\n"
+ "  var safeId = filename.replace(/[^a-zA-Z0-9]/g, '_');\n"
+ "  var bars = document.querySelectorAll('[id^=\"prog-' + safeId + '\"]');\n"
+ "  for (var i = 0; i < bars.length; i++) {\n"
+ "    bars[i].style.width = percent + '%';\n"
+ "  }\n"
+ "}\n"

+ "function onDownloadComplete(filename) {\n"
+ "  delete downloadingGames[filename];\n"
+ "  installedGames[filename] = true;\n"
// Find game name for toast
+ "  var gameName = filename;\n"
+ "  for (var i = 0; i < storeCatalog.length; i++) {\n"
+ "    if (storeCatalog[i].file === filename) { gameName = storeCatalog[i].name; break; }\n"
+ "  }\n"
+ "  showToast(gameName + ' installed successfully!');\n"
+ "  if (overlayOpen === 'store') {\n"
+ "    renderStore();\n"
+ "    updateStoreFocus();\n"
+ "  }\n"
+ "}\n"

+ "function onDownloadError(filename, error) {\n"
+ "  delete downloadingGames[filename];\n"
+ "  var gameName = filename;\n"
+ "  for (var i = 0; i < storeCatalog.length; i++) {\n"
+ "    if (storeCatalog[i].file === filename) { gameName = storeCatalog[i].name; break; }\n"
+ "  }\n"
+ "  showToast('Error downloading ' + gameName + ': ' + error);\n"
+ "  if (overlayOpen === 'store') {\n"
+ "    renderStore();\n"
+ "    updateStoreFocus();\n"
+ "  }\n"
+ "}\n"

// ===== SETTINGS OVERLAY =====
+ "function openSettingsOverlay() {\n"
+ "  try {\n"
+ "    document.getElementById('settingsGames').textContent = gameCount + ' games';\n"
+ "    var b = Console.getBatteryLevel();\n"
+ "    var ch = Console.isCharging();\n"
+ "    document.getElementById('settingsBatt').textContent = b + '%' + (ch ? ' (Charging)' : '');\n"
+ "    try {\n"
+ "      var ci2 = JSON.parse(Console.getControllerInfo());\n"
+ "      var ctrlText = ci2.connected ? ci2.name : (ci2.paired ? ci2.name + ' (paired)' : 'Not connected');\n"
+ "      if (ci2.connected && ci2.battery >= 0) ctrlText += '  (' + ci2.battery + '%)';\n"
+ "      document.getElementById('settingsCtrl').textContent = ctrlText;\n"
+ "    } catch(e2) { document.getElementById('settingsCtrl').textContent = controllerPaired ? controllerName : 'Not connected'; }\n"
+ "  } catch(e) {}\n"
+ "  document.getElementById('settingsOverlay').classList.add('show');\n"
+ "  settingsFocusIdx = 0;\n"
+ "  updateSettingsFocus();\n"
+ "  overlayOpen = 'settings';\n"
+ "}\n"

+ "function updateSettingsFocus() {\n"
+ "  document.getElementById('settingsShutdown').classList.remove('focused');\n"
+ "  document.getElementById('settingsReboot').classList.remove('focused');\n"
+ "  document.getElementById('settingsCloseBtn').classList.remove('focused');\n"
+ "  if (settingsFocusIdx === 0) document.getElementById('settingsShutdown').classList.add('focused');\n"
+ "  else if (settingsFocusIdx === 1) document.getElementById('settingsReboot').classList.add('focused');\n"
+ "  else document.getElementById('settingsCloseBtn').classList.add('focused');\n"
+ "}\n"

+ "function navigateSettings(dir) {\n"
+ "  playTick();\n"
+ "  if (dir === 'left') {\n"
+ "    if (settingsFocusIdx === 1) settingsFocusIdx = 0;\n"
+ "  } else if (dir === 'right') {\n"
+ "    if (settingsFocusIdx === 0) settingsFocusIdx = 1;\n"
+ "  } else if (dir === 'down') {\n"
+ "    if (settingsFocusIdx <= 1) settingsFocusIdx = 2;\n"
+ "  } else if (dir === 'up') {\n"
+ "    if (settingsFocusIdx === 2) settingsFocusIdx = 0;\n"
+ "  }\n"
+ "  updateSettingsFocus();\n"
+ "}\n"

+ "function selectSettingsItem() {\n"
+ "  playSelect();\n"
+ "  if (settingsFocusIdx === 0) doShutdown();\n"
+ "  else if (settingsFocusIdx === 1) doReboot();\n"
+ "  else closeOverlay();\n"
+ "}\n"

+ "function doShutdown() {\n"
+ "  try { Console.shutdownDevice(); } catch(e) { showToast('Shutdown failed'); }\n"
+ "}\n"
+ "function doReboot() {\n"
+ "  try { Console.rebootDevice(); } catch(e) { showToast('Reboot failed'); }\n"
+ "}\n"

+ "function closeOverlay() {\n"
+ "  document.getElementById('storeOverlay').classList.remove('show');\n"
+ "  document.getElementById('settingsOverlay').classList.remove('show');\n"
+ "  document.getElementById('filterOverlay').classList.remove('show');\n"
+ "  try { document.getElementById('settingsCloseBtn').classList.remove('focused'); } catch(e){}\n"
+ "  overlayOpen = null;\n"
+ "}\n"

// Filter overlay functions
+ "function openFilterOverlay() {\n"
+ "  filterTab = 0;\n"
+ "  filterFocusArea = 'grid';\n"
+ "  filterGridIdx = 0;\n"
+ "  renderFilterGrid();\n"
+ "  document.getElementById('filterOverlay').classList.add('show');\n"
+ "  overlayOpen = 'filter';\n"
+ "  updateFilterFocus();\n"
+ "}\n"

+ "function setFilterTab(tab) {\n"
+ "  filterTab = tab;\n"
+ "  filterGridIdx = 0;\n"
+ "  filterFocusArea = 'grid';\n"
+ "  renderFilterGrid();\n"
+ "  updateFilterFocus();\n"
+ "}\n"

+ "function renderFilterGrid() {\n"
+ "  var grid = document.getElementById('filterGrid');\n"
+ "  var html = '';\n"
// Update tab styles
+ "  document.getElementById('filterTabSys').className = 'filter-tab' + (filterTab === 0 ? ' active' : '');\n"
+ "  document.getElementById('filterTabGenre').className = 'filter-tab' + (filterTab === 1 ? ' active' : '');\n"
+ "  if (filterTab === 0) {\n"
// System tab: show category list
+ "    for (var i = 0; i < categories.length; i++) {\n"
+ "      var cat = categories[i];\n"
+ "      var isActive = (i === currentCat);\n"
+ "      var color = i === 0 ? 'var(--accent)' : sysColor(cat.name.toLowerCase().replace('game boy advance','gba').replace('game boy color','gbc').replace('game boy','gb').replace('nintendo','nes').replace('super nintendo','snes').replace('sega genesis','genesis'));\n"
+ "      html += '<div class=\"filter-item' + (isActive ? ' active' : '') + '\" onclick=\"selectFilter(' + i + ')\"'\n"
+ "        + ' style=\"border-left:3px solid ' + color + '\">';\n"
+ "      html += '<span class=\"fi-name\">' + cat.name + '</span>';\n"
+ "      html += '<span class=\"fi-count\">' + cat.games.length + ' games</span>';\n"
+ "      html += '</div>';\n"
+ "    }\n"
+ "    filterItemCount = categories.length;\n"
+ "  } else {\n"
// Genre tab: build genre counts and show
+ "    var genreCounts = {};\n"
+ "    var genreOrder = [];\n"
+ "    for (var i = 0; i < allGames.length; i++) {\n"
+ "      var genre = detectGenre(allGames[i].cleanName);\n"
+ "      if (!genreCounts[genre]) { genreCounts[genre] = 0; genreOrder.push(genre); }\n"
+ "      genreCounts[genre]++;\n"
+ "    }\n"
// Sort by count descending
+ "    genreOrder.sort(function(a,b) { return genreCounts[b] - genreCounts[a]; });\n"
+ "    for (var i = 0; i < genreOrder.length; i++) {\n"
+ "      var gn = genreOrder[i];\n"
+ "      var color = '#0070d1';\n"
+ "      for (var r = 0; r < GENRE_RULES.length; r++) {\n"
+ "        if (GENRE_RULES[r].name === gn) { color = GENRE_RULES[r].color; break; }\n"
+ "      }\n"
+ "      html += '<div class=\"filter-item\" onclick=\"selectGenre(\\'' + gn + '\\')\"'\n"
+ "        + ' style=\"border-left:3px solid ' + color + '\">';\n"
+ "      html += '<span class=\"fi-name\">' + gn + '</span>';\n"
+ "      html += '<span class=\"fi-count\">' + genreCounts[gn] + ' games</span>';\n"
+ "      html += '</div>';\n"
+ "    }\n"
+ "    filterItemCount = genreOrder.length;\n"
+ "  }\n"
+ "  grid.innerHTML = html;\n"
+ "}\n"

+ "function updateFilterFocus() {\n"
// Clear all focus states
+ "  var items = document.querySelectorAll('.filter-item');\n"
+ "  for (var i = 0; i < items.length; i++) items[i].classList.remove('focused');\n"
+ "  document.getElementById('filterTabSys').classList.remove('focused');\n"
+ "  document.getElementById('filterTabGenre').classList.remove('focused');\n"
+ "  document.getElementById('filterAllBtn').classList.remove('focused');\n"
// Apply focus to current area
+ "  if (filterFocusArea === 'tabs') {\n"
+ "    var tabEl = filterTab === 0 ? 'filterTabSys' : 'filterTabGenre';\n"
+ "    document.getElementById(tabEl).classList.add('focused');\n"
+ "  } else if (filterFocusArea === 'grid') {\n"
+ "    if (items[filterGridIdx]) items[filterGridIdx].classList.add('focused');\n"
+ "  } else if (filterFocusArea === 'allbtn') {\n"
+ "    document.getElementById('filterAllBtn').classList.add('focused');\n"
+ "  }\n"
+ "}\n"

+ "function navigateFilter(dir) {\n"
+ "  playTick();\n"
+ "  if (filterFocusArea === 'tabs') {\n"
+ "    if (dir === 'left' || dir === 'right') {\n"
+ "      filterTab = filterTab === 0 ? 1 : 0;\n"
+ "      renderFilterGrid();\n"
+ "      updateFilterFocus();\n"
+ "    } else if (dir === 'down') {\n"
+ "      filterFocusArea = 'grid';\n"
+ "      filterGridIdx = 0;\n"
+ "      updateFilterFocus();\n"
+ "    }\n"
+ "  } else if (filterFocusArea === 'grid') {\n"
+ "    if (dir === 'left') {\n"
+ "      filterGridIdx--;\n"
+ "      if (filterGridIdx < 0) filterGridIdx = filterItemCount - 1;\n"
+ "      updateFilterFocus();\n"
+ "    } else if (dir === 'right') {\n"
+ "      filterGridIdx++;\n"
+ "      if (filterGridIdx >= filterItemCount) filterGridIdx = 0;\n"
+ "      updateFilterFocus();\n"
+ "    } else if (dir === 'up') {\n"
+ "      var newIdx = filterGridIdx - FILTER_COLS;\n"
+ "      if (newIdx < 0) {\n"
+ "        filterFocusArea = 'tabs';\n"
+ "        updateFilterFocus();\n"
+ "      } else {\n"
+ "        filterGridIdx = newIdx;\n"
+ "        updateFilterFocus();\n"
+ "      }\n"
+ "    } else if (dir === 'down') {\n"
+ "      var newIdx = filterGridIdx + FILTER_COLS;\n"
+ "      if (newIdx >= filterItemCount) {\n"
+ "        filterFocusArea = 'allbtn';\n"
+ "        updateFilterFocus();\n"
+ "      } else {\n"
+ "        filterGridIdx = newIdx;\n"
+ "        updateFilterFocus();\n"
+ "      }\n"
+ "    } else if (dir === 'l1' || dir === 'r1') {\n"
+ "      filterTab = filterTab === 0 ? 1 : 0;\n"
+ "      filterGridIdx = 0;\n"
+ "      renderFilterGrid();\n"
+ "      updateFilterFocus();\n"
+ "    }\n"
+ "  } else if (filterFocusArea === 'allbtn') {\n"
+ "    if (dir === 'up') {\n"
+ "      filterFocusArea = 'grid';\n"
+ "      filterGridIdx = Math.min(filterGridIdx, filterItemCount - 1);\n"
+ "      updateFilterFocus();\n"
+ "    }\n"
+ "  }\n"
+ "}\n"

+ "function selectFilterItem() {\n"
+ "  playSelect();\n"
+ "  if (filterFocusArea === 'tabs') {\n"
// Pressing A on a tab activates it
+ "    setFilterTab(filterTab);\n"
+ "  } else if (filterFocusArea === 'grid') {\n"
+ "    if (filterTab === 0) {\n"
// System tab — select the category
+ "      selectFilter(filterGridIdx);\n"
+ "    } else {\n"
// Genre tab — select the genre
+ "      var items = document.querySelectorAll('.filter-item');\n"
+ "      if (items[filterGridIdx]) {\n"
+ "        var genreName = items[filterGridIdx].querySelector('.fi-name').textContent;\n"
+ "        selectGenre(genreName);\n"
+ "      }\n"
+ "    }\n"
+ "  } else if (filterFocusArea === 'allbtn') {\n"
+ "    selectFilter(-1);\n"
+ "  }\n"
+ "}\n"

+ "function selectFilter(catIdx) {\n"
+ "  if (catIdx >= 0 && catIdx < categories.length) {\n"
+ "    currentCat = catIdx;\n"
+ "  } else {\n"
// -1 means All Games — find it
+ "    for (var i = 0; i < categories.length; i++) {\n"
+ "      if (categories[i].name === 'All Games') { currentCat = i; break; }\n"
+ "    }\n"
+ "  }\n"
+ "  currentGameIdx = 0;\n"
+ "  closeOverlay();\n"
+ "  renderCarousel();\n"
+ "  showCatToast(categories[currentCat].name);\n"
+ "}\n"

+ "function selectGenre(genreName) {\n"
// Build a temporary genre category and inject it
+ "  var genreGames = [];\n"
+ "  for (var i = 0; i < allGames.length; i++) {\n"
+ "    if (detectGenre(allGames[i].cleanName) === genreName) genreGames.push(allGames[i]);\n"
+ "  }\n"
+ "  if (genreGames.length === 0) { closeOverlay(); return; }\n"
// Remove any previous genre category
+ "  categories = categories.filter(function(c) { return !c.isGenre; });\n"
// Insert genre category at position 1 (after Recently Played or at start)
+ "  var insertAt = (categories.length > 0 && categories[0].name === 'Recently Played') ? 1 : 0;\n"
+ "  categories.splice(insertAt, 0, {name:genreName, system:null, games:genreGames, isGenre:true});\n"
+ "  currentCat = insertAt;\n"
+ "  currentGameIdx = 0;\n"
+ "  closeOverlay();\n"
+ "  renderCarousel();\n"
+ "  renderCatPills();\n"
+ "  showCatToast(genreName + ' (' + genreGames.length + ')');\n"
+ "}\n"

// URL download function
+ "function downloadFromUrl() {\n"
+ "  var url = document.getElementById('storeUrlInput').value.trim();\n"
+ "  if (!url) { showToast('Enter a URL'); return; }\n"
+ "  var sys = document.getElementById('storeSysSelect').value;\n"
+ "  var filename = url.split('/').pop().split('?')[0];\n"
+ "  if (!filename || filename.indexOf('.') < 0) { filename = 'game_' + Date.now() + '.bin'; }\n"
+ "  document.getElementById('storeStatus').textContent = 'Downloading ' + filename + '...';\n"
+ "  document.getElementById('storeProgressFill').style.width = '0%';\n"
+ "  try { Console.downloadGame(url, sys, filename); } catch(e) { showToast('Download error: ' + e); }\n"
+ "}\n"
+ "function onDownloadProgress(pct, filename) {\n"
+ "  document.getElementById('storeProgressFill').style.width = Math.max(0,pct) + '%';\n"
+ "  document.getElementById('storeStatus').textContent = 'Downloading... ' + pct + '%';\n"
+ "}\n"
+ "function onDownloadComplete(filename) {\n"
+ "  document.getElementById('storeProgressFill').style.width = '100%';\n"
+ "  document.getElementById('storeStatus').textContent = filename + ' downloaded! Restart to play.';\n"
+ "  document.getElementById('storeUrlInput').value = '';\n"
+ "  showToast('Downloaded: ' + filename);\n"
+ "}\n"
+ "function onDownloadError(filename, msg) {\n"
+ "  document.getElementById('storeStatus').textContent = 'Error: ' + msg;\n"
+ "  document.getElementById('storeProgressFill').style.width = '0%';\n"
+ "  showToast('Download failed');\n"
+ "}\n"

// ===== TOAST =====
+ "function showToast(msg) {\n"
+ "  var t = document.getElementById('infoToast');\n"
+ "  t.textContent = msg;\n"
+ "  t.classList.add('show');\n"
+ "  clearTimeout(t._timer);\n"
+ "  t._timer = setTimeout(function() { t.classList.remove('show'); }, 3000);\n"
+ "}\n"

// ===== CLOCK =====
+ "function updateClock() {\n"
+ "  var now = new Date();\n"
+ "  var h = now.getHours();\n"
+ "  var m = now.getMinutes();\n"
+ "  var ampm = h >= 12 ? 'PM' : 'AM';\n"
+ "  h = h % 12; if (h === 0) h = 12;\n"
+ "  document.getElementById('clock').textContent = h + ':' + (m < 10 ? '0' : '') + m + ' ' + ampm;\n"
+ "}\n"

// ===== REFRESH STATUS =====
+ "function refreshStatus() {\n"
+ "  try {\n"
+ "    var batt = Console.getBatteryLevel();\n"
+ "    var charging = Console.isCharging();\n"
+ "    if (batt >= 0) {\n"
+ "      document.getElementById('battPct').textContent = batt + '%';\n"
+ "      var fill = document.getElementById('battFill');\n"
+ "      fill.style.width = batt + '%';\n"
+ "      fill.className = 'batt-fill ' + (batt > 50 ? 'high' : batt > 20 ? 'mid' : 'low');\n"
+ "      document.getElementById('chargeIcon').className = 'charge-icon' + (charging ? ' show' : '');\n"
+ "    }\n"
+ "  } catch(e) {}\n"
+ "  try {\n"
+ "    var ci = JSON.parse(Console.getControllerInfo());\n"
+ "    controllerPaired = ci.paired;\n"
+ "    controllerName = ci.name || '';\n"
+ "    var dot = document.getElementById('ctrlDot');\n"
+ "    var name = document.getElementById('ctrlName');\n"
+ "    var cbatt = document.getElementById('ctrlBatt');\n"
+ "    if (ci.connected) {\n"
+ "      dot.className = 'ctrl-dot on';\n"
+ "      name.textContent = ci.name || 'Controller';\n"
+ "      if (ci.battery >= 0) {\n"
+ "        cbatt.textContent = ci.battery + '%';\n"
+ "        cbatt.className = 'ctrl-batt' + (ci.battery <= 20 ? ' low' : '');\n"
+ "      } else {\n"
+ "        cbatt.textContent = '';\n"
+ "      }\n"
+ "    } else if (ci.paired) {\n"
+ "      dot.className = 'ctrl-dot paired';\n"
+ "      name.textContent = (ci.name || 'Controller') + ' (paired)';\n"
+ "      cbatt.textContent = '';\n"
+ "    } else {\n"
+ "      dot.className = 'ctrl-dot off';\n"
+ "      name.textContent = ci.enabled ? 'No Controller' : 'BT Off';\n"
+ "      cbatt.textContent = '';\n"
+ "    }\n"
+ "  } catch(e) {}\n"
+ "  try {\n"
+ "    gameCount = Console.getGameCount();\n"
+ "  } catch(e) {}\n"
+ "}\n"

// ===== INIT =====
+ "function init() {\n"
+ "  updateClock();\n"
+ "  setInterval(updateClock, 30000);\n"
+ "  refreshStatus();\n"
+ "  loadGames();\n"
+ "  renderCatPills();\n"
+ "  renderCarousel();\n"
+ "  focusRow = 0;\n"
// Dismiss splash after animation
+ "  setTimeout(function() {\n"
+ "    var s = document.getElementById('splash');\n"
+ "    if (s) { s.classList.add('hide'); setTimeout(function() { s.remove(); }, 800); }\n"
+ "  }, 2200);\n"
+ "}\n"

// ===== ON RESUME =====
+ "function onResume() {\n"
+ "  refreshStatus();\n"
+ "  loadGames();\n"
+ "  renderCatPills();\n"
+ "  renderCarousel();\n"
+ "}\n"

// Init on load
+ "document.addEventListener('DOMContentLoaded', init);\n"

+ "</script>\n"
+ "</body></html>";
    }
}
